#GUARDIAN STARS = Sun, Mercury, Venus, Moon, Mars, Jupiter, Saturn, Uranus, Neptune, and Pluto

	#"000010": {
	#"card_type": "Monster",
	#"card_name": "",
	#"attribute": "",
	#"level": 1,
	#"atk": 0,
	#"def": 0,
	#"type": "",
	#"guardian_star": ["Uranus","Venus"],
	#"description": "",
	#"effect": [
	#],
	#"tags": ["",""],
	#"passcode": "12345678"
	#},

const CARDS = { 
  "000000": {
	"card_id": "000000",
	"card_type": "Monster",
	"card_name": "Dark Magician",
	"attribute": "Dark",
	"level": 7,
	"atk": 2500,
	"def": 2100,
	"type": "Spellcaster",
	"description": "El hechicero supremo en terminos de Ataque y Defensa, sin embargo su máximo potencial aún no ha sido alcanzado.",
	"effect": [],
	"guardian_star": ["Mercury","Mars"],
	"tags": ["spellcaster", "dark", "sage"],
	"passcode": "46986414"
  },
	"000001": {
	"card_id": "000001",
	"card_type": "Monster",
	"card_name": "Doron",
	"attribute": "Earth",
	"level": 2,
	"atk": 900,
	"def": 500,
	"type": "Warrior",
	"guardian_star": ["Neptune","Moon"],
	"description": "Crea una ilusión de si mismo para atacar al oponente desde distintas direcciones.",
	"effect": [], #Maybe duplicate
	"tags": ["warrior","earth","doppel"],
	"passcode": "00756652"
  },
	"000002": {
	"card_id": "000002",
	"card_type": "Monster",
	"card_name": "Red-Eyes B. Dragon",
	"attribute": "Dark",
	"level": 7,
	"atk": 2400,
	"def": 2000,
	"type": "Dragon",
	"guardian_star": ["Neptune","Moon"],
	"description": "Feroz dragón con ataques mortales incluso sin haber alcanzado su maximo poder.",
	"effect": [],
	"tags": ["dragon","dark","red-eyes"],
	"passcode": "74677422"
  },
	"000003": {
	"card_id": "000003",
	"card_type": "Monster",
	"card_name": "Blue-Eyes White Dragon",
	"attribute": "light",
	"level": 8,
	"atk": 3000,
	"def": 2500,
	"type": "dragon",
	"guardian_star": ["Sun","Mars"],
	"description": "Este legendario dragón es una poderosa máquina de destrucción. Virtualmente invencible, muy pocos se han enfrentado a esta impresionante criatura y han vivido para contarlo.",
	"effect": [],
	"tags": ["dragon", "light", "blue-eyes"],
	"passcode": "89631139"
  },
	"000004": {
	"card_id": "000004",
	"card_type": "Spell",
	"card_name": "Raigeki",
	"attribute": "spell",
	"level": null,
	"atk": null,
	"def": null,
	"type": "spell",
	"guardian_star": [],
	"description": "Rayo con el poder de destruir a todos los adversarios.",
	"effect": [
		"destroy_card",
		"enemy_monsters"
	],
	"tags": [],
	"passcode": "12580477"
  },
	"000005": {
	"card_id": "000005",
	"card_type": "Monster",
	"card_name": "Asura Priest",
	"attribute": "Light",
	"level": 4,
	"atk": 1700,
	"def": 1200,
	"type": "Fairy",
	"guardian_star": ["Sun","Venus"],
	"description": "Sacerdote que ha heredado el poder de Asura, sus feroces ataques pueden alcanzar a todos los oponentes.",
	"effect": [
		"on_attack",
		"multi_attack", 
		"all_each"
	],
	"tags": ["priest","light","fairy","ethereal"],
	"passcode": "02134346"
  },
	"000006": {
	"card_id": "000006",
	"card_type": "Monster",
	"card_name": "Trent",
	"attribute": "Earth",
	"level": 5,
	"atk": 1500,
	"def": 1800,
	"type": "Plant",
	"guardian_star": ["Jupiter","Sun"],
	"description": "Un guardián de los bosques, se cree que este enorme árbol es inmortal.",
	"effect": [
	],
	"tags": ["wood","tree","plant","immortal","earth"],
	"passcode": "78780140"
  },
	"000007": {
	"card_id": "000007",
	"card_type": "Monster",
	"card_name": "Blue-Eyes Ultimate Dragon",
	"attribute": "Light",
	"level": 12,
	"atk": 4500,
	"def": 3800,
	"type": "Dragon",
	"guardian_star": ["Sun","Venus"],
	"description": "La forma definitiva de los Dragones de ojos azules, su poder de ataque es casi insuperable.",
	"effect": [
	],
	"tags": ["blue-eyes","dragon","light"],
	"passcode": "23995346"
  },
	"000008": {
	"card_id": "000008",
	"card_type": "Monster",
	"card_name": "Celtic Guardian",
	"attribute": "Earth",
	"level": 4,
	"atk": 1400,
	"def": 1200,
	"type": "Warrior",
	"guardian_star": ["Sun","Uranus"],
	"description": "Un elfo que aprendió a blandir la espada, combate a sus enemigos con ataques más veloces que el sonido",
	"effect": [
	],
	"tags": ["elf","warrior","earth"],
	"passcode": "91152256"
  },
	"000009": {
	"card_id": "000009",
	"card_type": "Monster",
	"card_name": "Dancing Elf",
	"attribute": "Light",
	"level": 1,
	"atk": 300,
	"def": 200,
	"type": "Fairy",
	"guardian_star": ["Jupiter","Sun"],
	"description": "Una elfa que danza a través del cielo mientras vuela con sus afiladas alas.",
	"effect": [
	],
	"tags": ["elf","fairy","female"],
	"passcode": "59983499"
  },
	"000010": {
	"card_id": "000010",
	"card_type": "Monster",
	"card_name": "M-Warrior #2",
	"attribute": "Light",
	"level": 3,
	"atk": 500,
	"def": 1000,
	"type": "Fairy",
	"guardian_star": ["Uranus","Venus"],
	"description": "Especializado en ataques combinados, su armadura lo protege de grandes daños, sin embargo su potencial se alcanza al combinar sus técnicas con otros.",
	"effect": [
	],
	"tags": ["warrior","armored","earth"],
	"passcode": "92731455"
},
	"000011": {
	"card_id": "000011",
	"card_type": "Monster",
	"card_name": "M-Warrior #1",
	"attribute": "Earth",
	"level": 3,
	"atk": 1000,
	"def": 500,
	"type": "Warrior",
	"guardian_star": ["Uranus","Venus"],
	"description": "Especializado en ataques combinados, este guerrero utiliza el magnetismo para bloquear la huída del enemigo, sin embargo su potencial se alcanza al combinar sus técnicas con otros",
	"effect": [
	],
	"tags": ["warrior","armored","earth"],
	"passcode": "56342351"
},
	"000012": {
	"card_id": "000012",
	"card_type": "Monster",
	"card_name": "Karbonala Warrior",
	"attribute": "Earth",
	"level": 4,
	"atk": 1500,
	"def": 1200,
	"type": "Warrior",
	"guardian_star": ["Uranus","Jupiter"],
	"description": "Un luchador completo en todo aspecto, superior a la media en cuanto a su factor de ataque.",
	"effect": [
	],
	"tags": ["warrior","earth","armored"],
	"passcode": "54541900"
	},
	"000013": {
	"card_id": "000013",
	"card_type": "Monster",
	"card_name": "Bio Plant",
	"attribute": "Dark",
	"level": 3,
	"atk": 600,
	"def": 1300,
	"type": "Plant",
	"guardian_star": ["Jupiter","Moon"],
	"description": "Una criatura monstruosa nacida de un error de laboratorio, sus mutaciones evolucionaron hasta otorgarle consciencia.",
	"effect": [
	],
	"tags": ["plant","dark","mutant"],
	"passcode": "07670542"
	},
	"000014": {
	"card_id": "000014",
	"card_type": "Monster",
	"card_name": "Gokibore",
	"attribute": "Earth",
	"level": 4,
	"atk": 1200,
	"def": 1400,
	"type": "Insect",
	"guardian_star": ["Jupiter","Moon"],
	"description": "Una grande y esférica cucaracha que ataca a sus enemigos rodando encima de ellos. Su duro caparazón lo vuelven un oponente formidable.",
	"effect": [
	],
	"tags": ["insect","earth"],
	"passcode": "15367030"
	},
	"000015": {
	"card_id": "000015",
	"card_type": "Monster",
	"card_name": "Leghul",
	"attribute": "Earth",
	"level": 1,
	"atk": 300,
	"def": 350,
	"type": "Insect",
	"guardian_star": ["Jupiter","Moon"],
	"description": "Insecto en extremo debil, su sigilo permite atacar a oponentes que parecen fuera de alcance.",
	"effect": [
		"on_attack",
		"only_direct"
	],
	"tags": ["insect","earth"],
	"passcode": "12472242"
	},
	"000016": {
	"card_id": "000016",
	"card_type": "Monster",
	"card_name": "Ancient elf",
	"attribute": "Light",
	"level": 4,
	"atk": 1450,
	"def": 1200,
	"type": "Spellcaster",
	"guardian_star": ["Sun","Pluto"],
	"description": "Se rumorea que ha vivido por miles de años, lidera un ejercito de espiritus para protegerse de sus enemigos.",
	"effect": [],
	"tags": ["elf","spellcaster","light","sage","immortal"],
	"passcode": "93221206"
	},
	"000017": {
	"card_id": "000017",
	"card_type": "Monster",
	"card_name": "Bone Mouse",
	"attribute": "Dark",
	"level": 1,
	"atk": 400,
	"def": 300,
	"type": "Zombie",
	"guardian_star": ["Moon","Pluto"],
	"description": "Una rata zombie que caza felinos.",
	"effect": [],
	"tags": ["zombie","mouse","dark","beast"],
	"passcode": "21239280"
	},
	"000018": {
	"card_id": "000018",
	"card_type": "Monster",
	"card_name": "Fire Eye",
	"attribute": "Fire",
	"level": 2,
	"atk": 800,
	"def": 600,
	"type": "Pyro",
	"guardian_star": ["Mars","Saturn"],
	"description": "Ojo envuelto en llamas que ataca a su objetivo con rafagas de fuego.",
	"effect": [],
	"tags": ["eye","fire","pyro"],
	"passcode": "88435542"
	},
	"000019": {
	"card_id": "000019",
	"card_type": "Monster",
	"card_name": "Flame Viper",
	"attribute": "Fire",
	"level": 2,
	"atk": 400,
	"def": 450,
	"type": "Pyro",
	"guardian_star": ["Mars","Pluto"],
	"description": "Una serpiente de fuego extremadamente veloz.",
	"effect": [],
	"tags": ["snake","fire","pyro"],
	"passcode": "02830619"
	},
	"000020": {
	"card_id": "000020",
	"card_type": "Monster",
	"card_name": "Fox Fire",
	"attribute": "Fire",
	"level": 2,
	"atk": 300,
	"def": 200,
	"type": "Pyro",
	"guardian_star": ["Mars","Uranus"],
	"description": "Pequeño zorro de fuego, se dice que solo puede verse en las noches, aquellos que lo siguen suelen temrinar en mal camino.",
	"effect": [],
	"tags": ["beast","fire","pyro"],
	"passcode": "88753985"
	},
	"000021": {
	"card_id": "000021",
	"card_type": "Monster",
	"card_name": "Ameba",
	"attribute": "Water",
	"level": 2,
	"atk": 300,
	"def": 350,
	"type": "Aqua",
	"guardian_star": ["Neptune","Moon"],
	"description": "Criatura babosa parecida a una ameba, atrapa a sus presas con su cuerpo pegajoso y los digiere lentamente.",
	"effect": [],
	"tags": ["water","aqua","slime"],
	"passcode": "95174353"
	},
	"000022": {
	"card_id": "000022",
	"card_type": "Monster",
	"card_name": "Candle of Fate",
	"attribute": "Dark",
	"level": 2,
	"atk": 300,
	"def": 350,
	"type": "Fiend",
	"guardian_star": ["Mars","Moon"],
	"description": "Se dice que el destino de un ser es revelado cuando las llamas de todos los dedos se extinguen.",
	"effect": [],
	"tags": ["fiend","dark","fire","candle"],
	"passcode": "47695416"
	},
	"000023": {
	"card_id": "000023",
	"card_type": "Monster",
	"card_name": "Gruesome Goo",
	"attribute": "Water",
	"level": 3,
	"atk": 1300,
	"def": 700,
	"type": "Aqua",
	"guardian_star": ["Mars","Moon"],
	"description": "Se ve como una simple masa mucosa, pero su poder es superior al de muchas criaturas.",
	"effect": [],
	"tags": ["aqua","water","slime"],
	"passcode": "65623423"
	},
}
