#GUARDIAN STARS = Sun, Mercury, Venus, Moon, Mars, Jupiter, Saturn, Uranus, Neptune, and Pluto

	#"000010": {
	#"card_type": "Monster",
	#"card_name": "",
	#"attribute": "",
	#"level": 1,
	#"atk": 0,
	#"def": 0,
	#"type": "",
	#"guardian_star": ["Uranus","Venus"],
	#"description": "",
	#"effects": [
	#],
	#"tags": ["",""],
	#"passcode": "12345678"
	#},

const CARDS = { 
  "000000": {
	"card_id": "000000",
	"card_type": "Monster",
	"card_name": "Dark Magician",
	"attribute": "Dark",
	"level": 7,
	"atk": 2500,
	"def": 2100,
	"type": "Spellcaster",
	"description": "El hechicero supremo en terminos de Ataque y Defensa, sin embargo su máximo potencial aún no ha sido alcanzado.",
	"effects": [],
	"guardian_star": ["Mercury","Mars"],
	"tags": ["spellcaster", "dark", "sage"],
	"passcode": "46986414"
  },
	"000001": {
	"card_id": "000001",
	"card_type": "Monster",
	"card_name": "Doron",
	"attribute": "Earth",
	"level": 2,
	"atk": 900,
	"def": 500,
	"type": "Warrior",
	"guardian_star": ["Neptune","Moon"],
	"description": "Crea una ilusión de si mismo para atacar al oponente desde distintas direcciones.",
	"effects": [], #Maybe duplicate
	"tags": ["warrior","earth","doppel"],
	"passcode": "00756652"
  },
	"000002": {
	"card_id": "000002",
	"card_type": "Monster",
	"card_name": "Red-Eyes B. Dragon",
	"attribute": "Dark",
	"level": 7,
	"atk": 2400,
	"def": 2000,
	"type": "Dragon",
	"guardian_star": ["Neptune","Moon"],
	"description": "Feroz dragón con ataques mortales incluso sin haber alcanzado su maximo poder.",
	"effects": [],
	"tags": ["dragon","dark","red-eyes"],
	"passcode": "74677422"
  },
	"000003": {
	"card_id": "000003",
	"card_type": "Monster",
	"card_name": "Blue-Eyes White Dragon",
	"attribute": "light",
	"level": 8,
	"atk": 3000,
	"def": 2500,
	"type": "dragon",
	"guardian_star": ["Sun","Mars"],
	"description": "Este legendario dragón es una poderosa máquina de destrucción. Virtualmente invencible, muy pocos se han enfrentado a esta impresionante criatura y han vivido para contarlo.",
	"effects": [],
	"tags": ["dragon", "light", "blue-eyes"],
	"passcode": "89631139"
},
	"000004": {
	"card_id": "000004",
	"card_type": "Spell",
	"card_name": "Raigeki",
	"attribute": "spell",
	"level": null,
	"atk": null,
	"def": null,
	"type": "spell",
	"guardian_star": [],
	"description": "Rayo con el poder de destruir a todos los adversarios.",
	"effects": [
		{
			"type": "spell_activation",
			"action": "destroy_enemy_monsters"
		}
	],
	"tags": [],
	"passcode": "12580477"
  },
	"000005": {
	"card_id": "000005",
	"card_type": "Monster",
	"card_name": "Asura Priest",
	"attribute": "Light",
	"level": 4,
	"atk": 1700,
	"def": 1200,
	"type": "Fairy",
	"guardian_star": ["Sun","Venus"],
	"description": "Sacerdote que ha heredado el poder de Asura, sus feroces ataques pueden alcanzar a todos los oponentes.",
	"effects": [
		{
			"type": "on_attack",
			"action": "multi_attack",
			"mode": "all_each"
		}
	],
	"tags": ["priest","light","fairy","ethereal"],
	"passcode": "02134346"
  },
	"000006": {
	"card_id": "000006",
	"card_type": "Monster",
	"card_name": "Trent",
	"attribute": "Earth",
	"level": 5,
	"atk": 1500,
	"def": 1800,
	"type": "Plant",
	"guardian_star": ["Jupiter","Sun"],
	"description": "Un guardián de los bosques, se cree que este enorme árbol es inmortal.",
	"effects": [
	],
	"tags": ["wood","tree","plant","immortal","earth"],
	"passcode": "78780140"
  },
	"000007": {
	"card_id": "000007",
	"card_type": "Monster",
	"card_name": "Blue-Eyes Ultimate Dragon",
	"attribute": "Light",
	"level": 12,
	"atk": 4500,
	"def": 3800,
	"type": "Dragon",
	"guardian_star": ["Sun","Venus"],
	"description": "La forma definitiva de los Dragones de ojos azules, su poder de ataque es casi insuperable.",
	"effects": [
	],
	"tags": ["blue-eyes","dragon","light"],
	"passcode": "23995346"
  },
	"000008": {
	"card_id": "000008",
	"card_type": "Monster",
	"card_name": "Celtic Guardian",
	"attribute": "Earth",
	"level": 4,
	"atk": 1400,
	"def": 1200,
	"type": "Warrior",
	"guardian_star": ["Sun","Uranus"],
	"description": "Un elfo que aprendió a blandir la espada, combate a sus enemigos con ataques más veloces que el sonido",
	"effects": [
	],
	"tags": ["elf","warrior","earth"],
	"passcode": "91152256"
  },
	"000009": {
	"card_id": "000009",
	"card_type": "Monster",
	"card_name": "Dancing Elf",
	"attribute": "Light",
	"level": 1,
	"atk": 300,
	"def": 200,
	"type": "Fairy",
	"guardian_star": ["Jupiter","Sun"],
	"description": "Una elfa que danza a través del cielo mientras vuela con sus afiladas alas.",
	"effects": [
	],
	"tags": ["elf","fairy","light"],
	"passcode": "59983499"
  },
	"000010": {
	"card_id": "000010",
	"card_type": "Monster",
	"card_name": "M-Warrior #2",
	"attribute": "Light",
	"level": 3,
	"atk": 500,
	"def": 1000,
	"type": "Fairy",
	"guardian_star": ["Uranus","Venus"],
	"description": "Especializado en ataques combinados, su armadura lo protege de grandes daños, sin embargo su potencial se alcanza al combinar sus técnicas con otros.",
	"effects": [
	],
	"tags": ["warrior","armored","earth"],
	"passcode": "92731455"
},
	"000011": {
	"card_id": "000011",
	"card_type": "Monster",
	"card_name": "M-Warrior #1",
	"attribute": "Earth",
	"level": 3,
	"atk": 1000,
	"def": 500,
	"type": "Warrior",
	"guardian_star": ["Uranus","Venus"],
	"description": "Especializado en ataques combinados, este guerrero utiliza el magnetismo para bloquear la huída del enemigo, sin embargo su potencial se alcanza al combinar sus técnicas con otros",
	"effects": [
	],
	"tags": ["warrior","armored","earth"],
	"passcode": "56342351"
},
	"000012": {
	"card_id": "000012",
	"card_type": "Monster",
	"card_name": "Karbonala Warrior",
	"attribute": "Earth",
	"level": 4,
	"atk": 1500,
	"def": 1200,
	"type": "Warrior",
	"guardian_star": ["Uranus","Jupiter"],
	"description": "Un luchador completo en todo aspecto, superior a la media en cuanto a su factor de ataque.",
	"effects": [
	],
	"tags": ["warrior","earth","armored"],
	"passcode": "54541900"
},
	"000013": {
	"card_id": "000013",
	"card_type": "Monster",
	"card_name": "Bio Plant",
	"attribute": "Dark",
	"level": 3,
	"atk": 600,
	"def": 1300,
	"type": "Plant",
	"guardian_star": ["Jupiter","Moon"],
	"description": "Una criatura monstruosa nacida de un error de laboratorio, sus mutaciones evolucionaron hasta otorgarle consciencia.",
	"effects": [
	],
	"tags": ["plant","dark","mutant"],
	"passcode": "07670542"
	},
	"000014": {
	"card_id": "000014",
	"card_type": "Monster",
	"card_name": "Gokibore",
	"attribute": "Earth",
	"level": 4,
	"atk": 1200,
	"def": 1400,
	"type": "Insect",
	"guardian_star": ["Jupiter","Moon"],
	"description": "Una grande y esférica cucaracha que ataca a sus enemigos rodando encima de ellos. Su duro caparazón lo vuelven un oponente formidable.",
	"effects": [
	],
	"tags": ["insect","earth"],
	"passcode": "15367030"
},
	"000015": {
	"card_id": "000015",
	"card_type": "Monster",
	"card_name": "Leghul",
	"attribute": "Earth",
	"level": 1,
	"atk": 300,
	"def": 350,
	"type": "Insect",
	"guardian_star": ["Jupiter","Moon"],
	"description": "Insecto en extremo debil, su sigilo permite atacar a oponentes que parecen fuera de alcance.",
	"effects": [
		{
			"type": "on_attack",
			"action": "only_direct_attack"
		}
	],
	"tags": ["insect","earth"],
	"passcode": "12472242"
},
	"000016": {
	"card_id": "000016",
	"card_type": "Monster",
	"card_name": "Ancient elf",
	"attribute": "Light",
	"level": 4,
	"atk": 1450,
	"def": 1200,
	"type": "Spellcaster",
	"guardian_star": ["Sun","Pluto"],
	"description": "Se rumorea que ha vivido por miles de años, lidera un ejercito de espiritus para protegerse de sus enemigos.",
	"effects": [],
	"tags": ["elf","spellcaster","light","sage","immortal"],
	"passcode": "93221206"
	},
	"000017": {
	"card_id": "000017",
	"card_type": "Monster",
	"card_name": "Bone Mouse",
	"attribute": "Dark",
	"level": 1,
	"atk": 400,
	"def": 300,
	"type": "Zombie",
	"guardian_star": ["Moon","Pluto"],
	"description": "Una rata zombie que caza felinos.",
	"effects": [],
	"tags": ["zombie","mouse","dark","beast"],
	"passcode": "21239280"
	},
	"000018": {
	"card_id": "000018",
	"card_type": "Monster",
	"card_name": "Fire Eye",
	"attribute": "Fire",
	"level": 2,
	"atk": 800,
	"def": 600,
	"type": "Pyro",
	"guardian_star": ["Mars","Saturn"],
	"description": "Ojo envuelto en llamas que ataca a su objetivo con rafagas de fuego.",
	"effects": [],
	"tags": ["eye","fire","pyro"],
	"passcode": "88435542"
	},
	"000019": {
	"card_id": "000019",
	"card_type": "Monster",
	"card_name": "Flame Viper",
	"attribute": "Fire",
	"level": 2,
	"atk": 400,
	"def": 450,
	"type": "Pyro",
	"guardian_star": ["Mars","Pluto"],
	"description": "Una serpiente de fuego extremadamente veloz.",
	"effects": [],
	"tags": ["snake","fire","pyro"],
	"passcode": "02830619"
	},
	"000020": {
	"card_id": "000020",
	"card_type": "Monster",
	"card_name": "Fox Fire",
	"attribute": "Fire",
	"level": 2,
	"atk": 300,
	"def": 200,
	"type": "Pyro",
	"guardian_star": ["Mars","Uranus"],
	"description": "Pequeño zorro de fuego, se dice que solo puede verse en las noches, aquellos que lo siguen suelen temrinar en mal camino.",
	"effects": [],
	"tags": ["beast","fire","pyro"],
	"passcode": "88753985"
},
	"000021": {
	"card_id": "000021",
	"card_type": "Monster",
	"card_name": "Ameba",
	"attribute": "Water",
	"level": 2,
	"atk": 300,
	"def": 350,
	"type": "Aqua",
	"guardian_star": ["Neptune","Moon"],
	"description": "Criatura babosa parecida a una ameba, atrapa a sus presas con su cuerpo pegajoso y los digiere lentamente.",
	"effects": [],
	"tags": ["water","aqua","slime"],
	"passcode": "95174353"
},
	"000022": {
	"card_id": "000022",
	"card_type": "Monster",
	"card_name": "Candle of Fate",
	"attribute": "Dark",
	"level": 2,
	"atk": 300,
	"def": 350,
	"type": "Fiend",
	"guardian_star": ["Mars","Moon"],
	"description": "Se dice que el destino de un ser es revelado cuando las llamas de todos los dedos se extinguen.",
	"effects": [],
	"tags": ["fiend","dark","fire","candle"],
	"passcode": "47695416"
	},
	"000023": {
	"card_id": "000023",
	"card_type": "Monster",
	"card_name": "Gruesome Goo",
	"attribute": "Water",
	"level": 3,
	"atk": 1300,
	"def": 700,
	"type": "Aqua",
	"guardian_star": ["Mars","Moon"],
	"description": "Se ve como una simple masa mucosa, pero su poder es superior al de muchas criaturas.",
	"effects": [],
	"tags": ["aqua","water","slime"],
	"passcode": "65623423"
	},
	"000024": {
	"card_id": "000024",
	"card_type": "Monster",
	"card_name": "Ancient Tree of Enlightenment",
	"attribute": "Earth",
	"level": 3,
	"atk": 600,
	"def": 1500,
	"type": "Plant",
	"guardian_star": ["Jupiter","Pluto"],
	"description": "Armado con gran conocimiento, este monstruo es capaz de resistir casi cualquier ataque.",
	"effects": [],
	"tags": ["tree","wood","sage","plant"],
	"passcode": "86421986"
	},
	"000025": {
	"card_id": "000025",
	"card_type": "Monster",
	"card_name": "Bolt Escargot",
	"attribute": "Water",
	"level": 5,
	"atk": 1400,
	"def": 1500,
	"type": "Thunder",
	"guardian_star": ["Pluto","Jupiter"],
	"description": "Esta criatura escupe una sustancia babosa que atrapa a sus enemigos dejándolos pegados, luego los paraliza con descargas eléctricas.",
	"effects": [],
	"tags": ["snail","thunder"],
	"passcode": "12146024"
	},
	"000026": {
	"card_id": "000026",
	"card_type": "Monster",
	"card_name": "Air Eater",
	"attribute": "Wind",
	"level": 6,
	"atk": 2100,
	"def": 1600,
	"type": "Fiend",
	"guardian_star": ["Moon","Saturn"],
	"description": "Un monstruo que acaba con sus presas absorbiendo todo el aire del entorno.",
	"effects": [],
	"tags": ["air","wind","fiend"],
	"passcode": "08353769"
	},
	"000027": {
	"card_id": "000027",
	"card_type": "Monster",
	"card_name": "Alinsection",
	"attribute": "Earth",
	"level": 3,
	"atk": 950,
	"def": 700,
	"type": "Insect",
	"guardian_star": ["Jupiter","Moon"],
	"description": "Un monstruo con forma de escarabajo ciervo, con cuernos y brazos dentados como sierras.",
	"effects": [],
	"tags": ["insect"],
	"passcode": "70924884"
	},
	"000028": {
	"card_id": "000028",
	"card_type": "Monster",
	"card_name": "Ancient Brain",
	"attribute": "Dark",
	"level": 3,
	"atk": 1000,
	"def": 700,
	"type": "Fiend",
	"guardian_star": ["Mercury","Moon"],
	"description": "Un sabio exiliado de la realidad, sus habilidades le permiten manipular energías oscuras.",
	"effects": [],
	"tags": ["sage","dark","fiend"],
	"passcode": "42431843"
	},
	"000029": {
	"card_id": "000029",
	"card_type": "Monster",
	"card_name": "Hurricail",
	"attribute": "Wind",
	"level": 2,
	"atk": 900,
	"def": 200,
	"type": "Spellcaster",
	"guardian_star": ["Saturn","Neptune"],
	"description": "Un tornado que arrasa los páramos, cortando a sus enemigos con cuchillas de viento.",
	"effects": [],
	"tags": ["wind","air"],
	"passcode": "15042735"
	},
	"000030": {
	"card_id": "000030",
	"card_type": "Monster",
	"card_name": "Armail",
	"attribute": "Earth",
	"level": 3,
	"atk": 700,
	"def": 1300,
	"type": "Warrior",
	"guardian_star": ["Mars","Mercury"],
	"description": "Un extraño guerrero que manipula tres terroríficas hojas, dos con sus manos y una con su cola.",
	"effects": [],
	"tags": ["warrior","weapon","armored"],
	"passcode": "53153481"
	},
	"000031": {
	"card_id": "000031",
	"card_type": "Monster",
	"card_name": "Big Eye",
	"attribute": "Dark",
	"level": 4,
	"atk": 1200,
	"def": 1000,
	"type": "Fiend",
	"guardian_star": ["Venus","Neptune"],
	"description": "Esta criatura está cubierta de ojos hipnóticos que adormecen a sus enemigos.",
	"effects": [],
	"tags": ["eye","fiend","dark"],
	"passcode": "16768387"
	},
	"000032": {
	"card_id": "000032",
	"card_type": "Monster",
	"card_name": "Dark King of the Abyss",
	"attribute": "Dark",
	"level": 3,
	"atk": 1200,
	"def": 800,
	"type": "Fiend",
	"guardian_star": ["Mercury","Pluto"],
	"description": "El Rey del Inframundo, se dice que una vez tuvo el poder para gobernar por sobre toda la oscuridad.",
	"effects": [],
	"tags": ["king","fiend","dark"],
	"passcode": "16768387"
	},
	"000033": {
	"card_id": "000033",
	"card_type": "Monster",
	"card_name": "Mysterious Puppeteer",
	"attribute": "Earth",
	"level": 4,
	"atk": 1000,
	"def": 1500,
	"type": "Warrior",
	"guardian_star": ["Uranus","Mercury"],
	"description": "Un maestro de marionetas que manipula a sus enemigos durante las batallas.",
	"effects": [],
	"tags": ["puppeteer","warrior"],
	"passcode": "54098121"
	},
	"000034": {
	"card_id": "000034",
	"card_type": "Monster",
	"card_name": "The Judgement Hand",
	"attribute": "Earth",
	"level": 3,
	"atk": 1400,
	"def": 700,
	"type": "Warrior",
	"guardian_star": ["Sun","Venus"],
	"description": "La mano del juicio final, es capaz de emitir intensos ataques que acaban con los malvados.",
	"effects": [],
	"tags": ["hand","warrior","judge"],
	"passcode": "28003512"
	},
	"000035": {
	"card_id": "000035",
	"card_type": "Monster",
	"card_name": "Lord of Zemia",
	"attribute": "Dark",
	"level": 4,
	"atk": 1300,
	"def": 1000,
	"type": "Fiend",
	"guardian_star": ["Mercury","Uranus"],
	"description": "Una malvada entidad que manipula a sus enemigos para guiarlos a su destrucción.",
	"effects": [],
	"tags": ["fiend","dark"],
	"passcode": "81618817"
	},
	"000036": {
	"card_id": "000036",
	"card_type": "Monster",
	"card_name": "Tainted Wisdom",
	"attribute": "Dark",
	"level": 3,
	"atk": 1250,
	"def": 800,
	"type": "Fiend",
	"guardian_star": ["Mercury","Uranus"],
	"description": "Un parásito cerebral que se aprovecha del conocimiento e inteligencia de aquellos a los que infecta.",
	"effects": [],
	"tags": ["fiend","dark","brain"],
	"passcode": "28725004"
	},
	"000037": {
	"card_id": "000037",
	"card_type": "Monster",
	"card_name": "Skull Knight",
	"attribute": "Dark",
	"level": 7,
	"atk": 2650,
	"def": 2250,
	"type": "Spellcaster",
	"guardian_star": ["Mercury","Neptune"],
	"description": "Monje que ha realizado gran cantidad de rituales en el inframundo, es capaz de utilizar la magia y la espada de manera experta.",
	"effects": [],
	"tags": ["Spellcaster","dark","skull"],
	"passcode": "02504891"
	},
	"000038": {
	"card_id": "000038",
	"card_type": "Monster",
	"card_name": "Man Eater",
	"attribute": "Earth",
	"level": 2,
	"atk": 800,
	"def": 600,
	"type": "Plant",
	"guardian_star": ["Mercury","Neptune"],
	"description": "Planta comehombres que utiliza sus tentáculos venenosos para atrapar a sus enemigos y devorarlos sin piedad.",
	"effects": [],
	"tags": ["plant"],
	"passcode": "93553943"
	},
	"000039": {
	"card_id": "000039",
	"card_type": "Monster",
	"card_name": "Firegrass",
	"attribute": "Earth",
	"level": 2,
	"atk": 700,
	"def": 600,
	"type": "Plant",
	"guardian_star": ["Mars","Moon"],
	"description": "Esta planta emana fuego de sus hojas, se dice que su cuerpo contiene el poder del fuego.",
	"effects": [],
	"tags": ["plant","fire","pyro"],
	"passcode": "53293545"
	},
	"000040": {
	"card_id": "000040",
	"card_type": "Monster",
	"card_name": "Hard Armor",
	"attribute": "Earth",
	"level": 3,
	"atk": 300,
	"def": 1200,
	"type": "Warrior",
	"guardian_star": ["Uranus","Sun"],
	"description": "Esta armadura tiene la capacidad de sacar a la luz las capacidades de aquellos guerreros que logren asimilarla.",
	"effects": [],
	"tags": ["warrior","armor"],
	"passcode": "20060230"
	},
	"000041": {
	"card_id": "000041",
	"card_type": "Monster",
	"card_name": "Gearfried the Iron Knight",
	"attribute": "Earth",
	"level": 4,
	"atk": 1800,
	"def": 1600,
	"type": "Warrior",
	"guardian_star": ["Uranus","Jupiter"],
	"description": "Este caballero posee una armadura tan poderosa que funciona tanto para atacar como defender, sin embargo se dice que su verdadero potencial se alcanza cuando la armadura se desprende de él.",
	"effects": [],
	"tags": ["warrior","armor"],
	"passcode": "00423705"
	},
	"000042": {
	"card_id": "000042",
	"card_type": "Monster",
	"card_name": "Larvas",
	"attribute": "Earth",
	"level": 3,
	"atk": 800,
	"def": 1000,
	"type": "Beast",
	"guardian_star": ["Jupiter","Mercury"],
	"description": "Una bestia similar a un ave, sus movimientos ágiles son casi invisibles, ataca a sus presas con sus brazos cortantes.",
	"effects": [],
	"tags": ["beast","winged-beast"],
	"passcode": "94675535"
	},
	"000043": {
	"card_id": "000043",
	"card_type": "Monster",
	"card_name": "Fire Reaper",
	"attribute": "Fire",
	"level": 3,
	"atk": 700,
	"def": 500,
	"type": "Zombie",
	"guardian_star": ["Mars","Sun"],
	"description": "Criatura resucitada que impone castigo con sus flechas llameantes.",
	"effects": [],
	"tags": ["zombie","skull","fire","pyro"],
	"passcode": "53581214"
	},
	"000044": {
	"card_id": "000044",
	"card_type": "Monster",
	"card_name": "Dokuroizo the Grim Reaper",
	"attribute": "Dark",
	"level": 3,
	"atk": 900,
	"def": 1200,
	"type": "Zombie",
	"guardian_star": ["Moon","Pluto"],
	"description": "Un espiritu viviente que caza la escencia vital de sus enemigos.",
	"effects": [],
	"tags": ["zombie","skull"],
	"passcode": "25882881"
	},
	"000045": {
	"card_id": "000045",
	"card_type": "Monster",
	"card_name": "Rhaimundos of the Red Sword",
	"attribute": "Earth",
	"level": 4,
	"atk": 1200,
	"def": 1300,
	"type": "Warrior",
	"guardian_star": ["Neptune","Mars"],
	"description": "Poderoso guerrero armado con una espada de fuego carmesí. Controla el fuego para cortar el movimiento de sus oponentes.",
	"effects": [],
	"tags": ["warrior","fire"],
	"passcode": "62403074"
	},
	"000046": {
	"card_id": "000046",
	"card_type": "Monster",
	"card_name": "Akihiron",
	"attribute": "Water",
	"level": 5,
	"atk": 1700,
	"def": 1400,
	"type": "Aqua",
	"guardian_star": ["Neptune","Jupiter"],
	"description": "Extraño insecto que mora en lo profundo de los mares.",
	"effects": [],
	"tags": ["insect","water","aqua"],
	"passcode": "36904469"
	},
	"000047": {
	"card_id": "000047",
	"card_type": "Monster",
	"card_name": "The Shadow Who Controls the Dark",
	"attribute": "Dark",
	"level": 3,
	"atk": 800,
	"def": 700,
	"type": "Fiend",
	"guardian_star": ["Mercury","Jupiter"],
	"description": "Una sombra viviente que habita en el reino de las tinieblas. Paraliza a sus enemigos para impedir sus ataques, en ocasiones trabaja con aliados, actuando como una capa mágica.",
	"effects": [],
	"tags": ["dark","shadow","robe"],
	"passcode": "63125616"
	},
	"000048": {
	"card_id": "000048",
	"card_type": "Monster",
	"card_name": "Monster Egg",
	"attribute": "Earth",
	"level": 3,
	"atk": 600,
	"def": 900,
	"type": "Warrior",
	"guardian_star": ["Uranus","Jupiter"],
	"description": "Un guerrero oculto dentro de un gran huevo, ataca a sus oponentes lanzándoles trozos de cáscara de huevo.",
	"effects": [],
	"tags": ["egg","warrior"],
	"passcode": "36121917"
	},#00732302
	"000049": {
	"card_id": "000049",
	"card_type": "Monster",
	"card_name": "Temple of Skulls",
	"attribute": "Dark",
	"level": 3,
	"atk": 800,
	"def": 1300,
	"type": "Zombie",
	"guardian_star": ["Mercury","Pluto"],
	"description": "Un templo extraño hecho de craneos y huesos, succiona la escencia vital de aquellos que atraviesen sus puertas.",
	"effects": [],
	"tags": ["zombie","skull"],
	"passcode": "00732302"
	},
	"000050": {
	"card_id": "000050",
	"card_type": "Monster",
	"card_name": "The Bewitching Phantom Thief",
	"attribute": "Dark",
	"level": 2,
	"atk": 700,
	"def": 700,
	"type": "Spellcaster",
	"guardian_star": ["Venus","Pluto"],
	"description": "Un ladrón llamativo, vestido con una capa oscura, que empuña un bastón mágico.",
	"effects": [],
	"tags": ["spellcaster","thief"],
	"passcode": "24348204"
	},
	"000051": {
	"card_id": "000051",
	"card_type": "Monster",
	"card_name": "Djinn the Watcher of the Wind",
	"attribute": "Wind",
	"level": 3,
	"atk": 700,
	"def": 900,
	"type": "Spellcaster",
	"guardian_star": ["Saturn","Mercury"],
	"description": "Controla las corrientes de aire para crear vientos violentos y tornados que expulsan a sus enemigos.",
	"effects": [],
	"tags": ["spellcaster","wind","air"],
	"passcode": "97843505"
	},
	"000052": {
	"card_id": "000052",
	"card_type": "Monster",
	"card_name": "Necrolancer the Timelord",
	"attribute": "Dark",
	"level": 3,
	"atk": 800,
	"def": 900,
	"type": "Spellcaster",
	"guardian_star": ["Venus","Uranus"],
	"description": "El primero de una serie de gólems que aparecen prácticamente en cualquier lugar saliendo de un anillo dimensional.",
	"effects": [],
	"tags": ["golem","timelord"],
	"passcode": "61454890"
	},
	"000053": {
	"card_id": "000053",
	"card_type": "Monster",
	"card_name": "Flame Manipulator",
	"attribute": "Fire",
	"level": 3,
	"atk": 900,
	"def": 1000,
	"type": "Spellcaster",
	"guardian_star": ["Mars","Pluto"],
	"description": "Ataca a los enemigos con hechizos relacionados con el fuego, como el Mar de Llamas y el Muro de Fuego.",
	"effects": [],
	"tags": ["fire","spellcaster","pyro"],
	"passcode": "34460851"
	},
	"000054": {
	"card_id": "000054",
	"card_type": "Monster",
	"card_name": "Toad Master",
	"attribute": "Water",
	"level": 3,
	"atk": 1000,
	"def": 1000,
	"type": "Aqua",
	"guardian_star": ["Neptune","Venus"],
	"description": "Con miles de años de antigüedad, este mago rana ataca a sus enemigos con un ejército de renacuajos.",
	"effects": [],
	"tags": ["aqua","spellcaster","water","toad"],
	"passcode": "62671448"
	},
	"000055": {
	"card_id": "000055",
	"card_type": "Monster",
	"card_name": "Blue-eyed Silver Zombie",
	"attribute": "Dark",
	"level": 3,
	"atk": 900,
	"def": 700,
	"type": "Zombie",
	"guardian_star": ["Sun","Pluto"],
	"description": "Una criatura de la que se rumorea que convierte a sus enemigos en zombis con un extraño rayo que emana de sus ojos.",
	"effects": [],
	"tags": ["dark","zombie","eye"],
	"passcode": "35282433"
	},
	"000056": {
	"card_id": "000056",
	"card_type": "Monster",
	"card_name": "Dragon Statue",
	"attribute": "Earth",
	"level": 3,
	"atk": 1100,
	"def": 900,
	"type": "Warrior",
	"guardian_star": ["Uranus","Mars"],
	"description": "Un guerrero de granito con alma de dragón empuña una poderosa espada contra todos sus enemigos.",
	"effects": [],
	"tags": ["earth","statue","dragon","warrior"],
	"passcode": "09197735"
	},
	"000057": {
	"card_id": "000057",
	"card_type": "Monster",
	"card_name": "Mystery Hand",
	"attribute": "Dark",
	"level": 2,
	"atk": 500,
	"def": 500,
	"type": "Warrior",
	"guardian_star": ["Moon","Uranus"],
	"description": "Retorciendo el tejido de la realidad, brazos se extienden desde otra dimensión para atacar a los oponentes.",
	"effects": [],
	"tags": ["hand","dark","spellcaster"],
	"passcode": "62793020"
	},
	"000058": {
	"card_id": "000058",
	"card_type": "Monster",
	"card_name": "Witty Phantom",
	"attribute": "Dark",
	"level": 4,
	"atk": 1400,
	"def": 1300,
	"type": "Fiend",
	"guardian_star": ["Mercury","Mars"],
	"description": "Vestido con un esmoquin negro como la noche, esta criatura preside sobre los condenados.",
	"effects": [],
	"tags": ["fiend","dark","spellcaster"],
	"passcode": "36304921"
	},
	"000059": {
	"card_id": "000059",
	"card_type": "Monster",
	"card_name": "Charubin the Fire Knight",
	"attribute": "Fire",
	"level": 3,
	"atk": 1100,
	"def": 800,
	"type": "Pyro",
	"guardian_star": ["Mars","Uranus"],
	"description": "Un guerrero protegido por un caparazón capaz incluso de desviar el calor de las llamas ardientes.",
	"effects": [],
	"tags": ["fire","pyro","warrior","armored"],
	"passcode": "37421579"
	},
	"000060": {
	"card_id": "000060",
	"card_type": "Monster",
	"card_name": "The 13th Grave",
	"attribute": "Dark",
	"level": 3,
	"atk": 1200,
	"def": 900,
	"type": "Pyro",
	"guardian_star": ["Moon","Pluto"],
	"description": "Un zombi que apareció repentinamente de la parcela número 13, supuestamente una tumba vacía.",
	"effects": [],
	"tags": ["zombie"],
	"passcode": "00032864"
	},
	"000061": {
	"card_id": "000061",
	"card_type": "Monster",
	"card_name": "Octoberser",
	"attribute": "Water",
	"level": 3,
	"atk": 1600,
	"def": 1400,
	"type": "Aqua",
	"guardian_star": ["Neptune","Moon"],
	"description": "Una extraña criatura con cabeza de pez y tentáculos de pulpo que ataca a sus enemigos con lanzas.",
	"effects": [],
	"tags": ["water","aqua","tentacle"],
	"passcode": "74637266"
	},
	"000062": {
	"card_id": "000062",
	"card_type": "Monster",
	"card_name": "Nemuriko",
	"attribute": "Dark",
	"level": 3,
	"atk": 800,
	"def": 700,
	"type": "Spellcaster",
	"guardian_star": ["Mercury","Moon"],
	"description": "Una criatura de aspecto infantil que controla un espíritu del sueño para sumir a sus enemigos en un sueño eterno.",
	"effects": [],
	"tags": ["tentacle","spellcaster"],
	"passcode": "90963488"
	},
	"000063": {
	"card_id": "000063",
	"card_type": "Monster",
	"card_name": "LaMoon",
	"attribute": "Light",
	"level": 5,
	"atk": 1200,
	"def": 1700,
	"type": "Spellcaster",
	"guardian_star": ["Sun","Uranus"],
	"description": "Una hechicera llegada desde la luna, ataca a los oponentes con potentes rayos de luz plateada.",
	"effects": [],
	"tags": ["spellcaster","light","fairy"],
	"passcode": "75850803"
	},
	"000064": {
	"card_id": "000064",
	"card_type": "Monster",
	"card_name": "Ansatsu",
	"attribute": "Earth",
	"level": 5,
	"atk": 1700,
	"def": 1200,
	"type": "Warrior",
	"guardian_star": ["Mercury","Neptune"],
	"description": "Un guerrero silencioso y veloz, especializado en ataques furtivos.",
	"effects": [],
	"tags": ["ninja","warrior"],
	"passcode": "48365709"
	},
	"000065": {
	"card_id": "000065",
	"card_type": "Monster",
	"card_name": "Faith Bird",
	"attribute": "Wind",
	"level": 4,
	"atk": 1500,
	"def": 1100,
	"type": "Winged-beast",
	"guardian_star": ["Sun","Jupiter"],
	"description": "Un ave de larga cola que ataca a sus rivales emanando luz de todo su ser.",
	"effects": [],
	"tags": ["bird","wind","winged-beast","light"],
	"passcode": "75582395"
	},
	"000066": {
	"card_id": "000066",
	"card_type": "Monster",
	"card_name": "Ancient Tool",
	"attribute": "Dark",
	"level": 5,
	"atk": 1700,
	"def": 1400,
	"type": "Machine",
	"guardian_star": ["Moon","Saturn"],
	"description": "Un motor de destrucción descubierto en las ruinas de una antigua civilización.",
	"effects": [],
	"tags": ["drill","machine"],
	"passcode": "49587396"
	},
	"000067": {
	"card_id": "000067",
	"card_type": "Monster",
	"card_name": "Dark Plant",
	"attribute": "Dark",
	"level": 1,
	"atk": 300,
	"def": 400,
	"type": "Plant",
	"guardian_star": ["Moon","Jupiter"],
	"description": "Una flor maligna, cultivada en suelo contaminado y fertilizada por fuerzas oscuras.",
	"effects": [],
	"tags": ["dark","plant"],
	"passcode": "13193642"
	},
	"000068": {
	"card_id": "000068",
	"card_type": "Monster",
	"card_name": "Yamata-no Dragon Scroll",
	"attribute": "Wind",
	"level": 2,
	"atk": 900,
	"def": 300,
	"type": "Dragon",
	"guardian_star": ["Saturn","Venus"],
	"description": "Este dragón es invocado a partir de un pergamino ilustrado para atacar a los enemigos. Sus escritos describen sabiduría perdida.",
	"effects": [],
	"tags": ["dragon","wind","book"],
	"passcode": "76704943"
	},
	"000069": {
	"card_id": "000069",
	"card_type": "Monster",
	"card_name": "Sleeping Lion",
	"attribute": "Earth",
	"level": 4,
	"atk": 700,
	"def": 1700,
	"type": "Beast",
	"guardian_star": ["Jupiter","Sun"],
	"description": "Frecuentemente se encuentra durmiendo, sin embargo, puede ser muy peligroso mientras está despierto.",
	"effects": [],
	"tags": ["beast","earth"],
	"passcode": "40200834"
	},
	"000070": {
	"card_id": "000070",
	"card_type": "Monster",
	"card_name": "Dream Clown",
	"attribute": "Earth",
	"level": 3,
	"atk": 1200,
	"def": 900,
	"type": "Warrior",
	"guardian_star": ["Venus","Saturn"],
	"description": "La danza de este mistrioso pallaso lleva a quienes la observan a un sueño profundo.",
	"effects": [],
	"tags": ["warrior","clown"],
	"passcode": "13215230"
	},
	"000071": {
	"card_id": "000071",
	"card_type": "Monster",
	"card_name": "Armed Ninja",
	"attribute": "Earth",
	"level": 1,
	"atk": 300,
	"def": 300,
	"type": "Warrior",
	"guardian_star": ["Neptune","Mars"],
	"description": "Un ninja azul que ataca con una gran guadaña.",
	"effects": [],
	"tags": ["ninja","warrior"],
	"passcode": "09076207"
	},
	"000072": {
	"card_id": "000072",
	"card_type": "Monster",
	"card_name": "Queen Bird",
	"attribute": "Wind",
	"level": 5,
	"atk": 1200,
	"def": 2000,
	"type": "Winged-beast",
	"guardian_star": ["Saturn","Moon"],
	"description": "Un gran ave que ataca a sus enemigos con su largo pico.",
	"effects": [],
	"tags": ["wind","winged-beast"],
	"passcode": "73081602"
	},
	"000073": {
	"card_id": "000073",
	"card_type": "Monster",
	"card_name": "Crimson Sunbird",
	"attribute": "Fire",
	"level": 6,
	"atk": 2300,
	"def": 1800,
	"type": "Winged-beast",
	"guardian_star": ["Mars","Mercury"],
	"description": "Un gran ave que ataca a sus enemigos con su largo pico.",
	"effects": [],
	"tags": ["fire","pyro","winged-beast"],
	"passcode": "46696593"
	},
	"000074": {
	"card_id": "000074",
	"card_type": "Monster",
	"card_name": "Niwatori",
	"attribute": "Earth",
	"level": 3,
	"atk": 900,
	"def": 800,
	"type": "Winged-beast",
	"guardian_star": ["Jupiter","Venus"],
	"description": "Traga a sus enemigos enteros para alimentarse de su escencia completa.",
	"effects": [],
	"tags": ["bird","winged-beast"],
	"passcode": "07805359"
	},
	"000075": {
	"card_id": "000075",
	"card_type": "Monster",
	"card_name": "Mega Thunderball",
	"attribute": "Wind",
	"level": 2,
	"atk": 750,
	"def": 600,
	"type": "Thunder",
	"guardian_star": ["Pluto","Mercury"],
	"description": "Rueda sobre sus oponentes liberando descargas eléctricas.",
	"effects": [],
	"tags": ["ball","thunder"],
	"passcode": "21817254"
	},
	"000076": {
	"card_id": "000076",
	"card_type": "Monster",
	"card_name": "Mechaleon",
	"attribute": "Water",
	"level": 2,
	"atk": 800,
	"def": 600,
	"type": "Reptile",
	"guardian_star": ["Neptune","Saturn"],
	"description": "Un camaleón máquina que se oculta a la perfección cambiando sus colores.",
	"effects": [],
	"tags": ["reptile","water","machine"],
	"passcode": "94412545"
	},
	"000077": {
	"card_id": "000077",
	"card_type": "Monster",
	"card_name": "Kamakiriman",
	"attribute": "Earth",
	"level": 4,
	"atk": 1150,
	"def": 1400,
	"type": "Insect",
	"guardian_star": ["Jupiter","Moon"],
	"description": "Una mantis con forma humana y dos guadañas afiladas como navajas.",
	"effects": [],
	"tags": ["insect","earth"],
	"passcode": "68928540"
	},
	"000078": {
	"card_id": "000078",
	"card_type": "Monster",
	"card_name": "Kwagar Hercules",
	"attribute": "Earth",
	"level": 6,
	"atk": 1900,
	"def": 1700,
	"type": "Insect",
	"guardian_star": ["Jupiter","Sun"],
	"description": "Un monstruo insectoide con las mandíbulas de un escarabajo ciervo y el cuerno de un escarabajo.",
	"effects": [],
	"tags": ["insect","earth"],
	"passcode": "95144193"
	},
	"000079": {
	"card_id": "000079",
	"card_type": "Monster",
	"card_name": "Gemini Elf",
	"attribute": "Earth",
	"level": 4,
	"atk": 1900,
	"def": 900,
	"type": "Spellcaster",
	"guardian_star": ["Sun","Uranus"],
	"description": "Elfas gemelas que atacan a sus oponentes desde distintos ángulos.",
	"effects": [],
	"tags": ["elf","spellcaster"],
	"passcode": "69140098"
	},
	"000080": {
	"card_id": "000080",
	"card_type": "Monster",
	"card_name": "Mystical Sand",
	"attribute": "Earth",
	"level": 6,
	"atk": 2100,
	"def": 1700,
	"type": "Rock",
	"guardian_star": ["Mercury","Saturn"],
	"description": "Convierte a los enemigos en piedra y los reduce a polvo.",
	"effects": [],
	"tags": ["elf","spellcaster"],
	"passcode": "32751480"
	},
	"000081": {
	"card_id": "000081",
	"card_type": "Monster",
	"card_name": "Eldeen",
	"attribute": "Light",
	"level": 3,
	"atk": 950,
	"def": 1000,
	"type": "Spellcaster",
	"guardian_star": ["Mercury","Moon"],
	"description": "Hechicera entrenada para el combate, capáz de lanzar varios conjuros a la vez.",
	"effects": [],
	"tags": ["light","spellcaster"],
	"passcode": "06367785"
	},
	"000082": {
	"card_id": "000082",
	"card_type": "Monster",
	"card_name": "Flame Cerebrus",
	"attribute": "Fire",
	"level": 3,
	"atk": 2100,
	"def": 1800,
	"type": "Pyro",
	"guardian_star": ["Mars","Pluto"],
	"description": "Bestia flamígera que acaba con sus oponentes con su aliento ardiente.",
	"effects": [],
	"tags": ["fire","pyro","beast"],
	"passcode": "60862676"
},
"000083": {
	"card_id": "000083",
	"card_type": "Monster",
	"card_name": "Milus Radiant",
	"attribute": "Earth",
	"level": 1,
	"atk": 300,
	"def": 250,
	"type": "Beast",
	"guardian_star": ["Jupiter","Neptune"],
	"description": "Suelen subestimarla por su bajo poder, sin embargo su presencia potencia a aquellos que saben apreciarlo.",
	"effects": [
		{
			"type": "on_field",
			"action": "increase_atk_def",
			"amount": 500,
			"stat": "atk",
			"target": "earth_allies"
		}
	],
	"tags": ["beast","earth","aura"],
	"passcode": "07489323"
},
	"000084": {
	"card_id": "000084",
	"card_type": "Monster",
	"card_name": "Neck Hunter",
	"attribute": "Dark",
	"level": 6,
	"atk": 1750,
	"def": 1900,
	"type": "Fiend",
	"guardian_star": ["Moon","Uranus"],
	"description": "Armado con una enorme hoz, este monstruo puede disparar rayos desde sus grandes ojos.",
	"effects": [],
	"tags": ["dark","fiend"],
	"passcode": "70084224"
	},
	"000085": {
	"card_id": "000085",
	"card_type": "Monster",
	"card_name": "Spirit of the Mountain",
	"attribute": "Earth",
	"level": 5,
	"atk": 1300,
	"def": 1800,
	"type": "Spellcaster",
	"guardian_star": ["Uranus","Jupiter"],
	"description": "La musica que su cuerno produce puede apaciguar la furia de aquellos que la escuchen.",
	"effects": [],
	"tags": ["earth","spellcaster"],
	"passcode": "34690519"
},
	"000086": {
	"card_id": "000086",
	"card_type": "Monster",
	"card_name": "Starboy",
	"attribute": "Water",
	"level": 2,
	"atk": 550,
	"def": 500,
	"type": "Aqua",
	"guardian_star": ["Neptune","Mars"],
	"description": "Una forma de vida extraterrestre que se asentó en las profundidades de los oceanos, aquellas entidades afines al agua que lo rodeen ven sus capacidades incrementadas.",
	"effects": [
		{
			"type": "on_field",
			"action": "increase_atk_def",
			"amount": 400,
			"stat": "both",
			"target": "water_allies"
		}
	],
	"tags": ["aqua","water"],
	"passcode": "08201910"
},
	"000087": {
	"card_id": "000087",
	"card_type": "Monster",
	"card_name": "Monstrous Bird",
	"attribute": "Wind",
	"level": 6,
	"atk": 2000,
	"def": 1900,
	"type": "Winged-Beast",
	"guardian_star": ["Saturn","Mercury"],
	"description": "Un ave inmensa que sobrevuela los campos en busca de presas de gran tamaño, sus ataques son veloces e impredecibles.",
	"effects": [],
	"tags": ["wind","winged-beast"],
	"passcode": "35712107"
	},
	"000088": {
	"card_id": "000088",
	"card_type": "Monster",
	"card_name": "Skull Bird",
	"attribute": "Wind",
	"level": 6,
	"atk": 1900,
	"def": 1700,
	"type": "Winged-Beast",
	"guardian_star": ["Saturn","Venus"],
	"description": "Esta criatura es la forma que toman aquellas aves que se alimentan de numerosos cadaveres de criaturas malditas, su cuerpo ahora emana un aura corrupta.",
	"effects": [],
	"tags": ["wind","winged-beast","skull"],
	"passcode": "08327462"
	},
	"000089": {
	"card_id": "000089",
	"card_type": "Monster",
	"card_name": "Turtle Bird",
	"attribute": "Water",
	"level": 6,
	"atk": 1900,
	"def": 1700,
	"type": "Winged-Beast",
	"guardian_star": ["Saturn","Venus"],
	"description": "Una extraña criatura voladora con la capacidad de nadar y volar a igual velocidad.",
	"effects": [],
	"tags": ["water","winged-beast","turtle"],
	"passcode": "72929454"
	},
	"000090": {
	"card_id": "000090",
	"card_type": "Monster",
	"card_name": "Fire Kraken",
	"attribute": "Fire",
	"level": 4,
	"atk": 1600,
	"def": 1500,
	"type": "Aqua",
	"guardian_star": ["Mars","Saturn"],
	"description": "Un pulpo flamígero que puede mantener sus llamas encendidas incluso bajo el agua.",
	"effects": [],
	"tags": ["water","fire","aqua","tentacle"],
	"passcode": "46534755"
	},
	"000091": {
	"card_id": "000091",
	"card_type": "Monster",
	"card_name": "Boulder Tortoise",
	"attribute": "Earth",
	"level": 6,
	"atk": 1450,
	"def": 2200,
	"type": "Aqua",
	"guardian_star": ["Uranus","Neptune"],
	"description": "Una tortuga que ha endurecido su caparazón a un gran nivel, se cree que es mas duro que una roca.",
	"effects": [],
	"tags": ["earth","rock","turtle","aqua"],
	"passcode": "09540040"
	},
	"000092": {
	"card_id": "000092",
	"card_type": "Monster",
	"card_name": "Sand Stone",
	"attribute": "Earth",
	"level": 5,
	"atk": 1300,
	"def": 1600,
	"type": "Rock",
	"guardian_star": ["Uranus","Mars"],
	"description": "Esta extraña criatura emerge desde bajo tierra para atrapar a sus presas con sus largos y extraños tentáculos.",
	"effects": [],
	"tags": ["earth","rock","tentacle"],
	"passcode": "73051941"
	},
	"000093": {
	"card_id": "000093",
	"card_type": "Monster",
	"card_name": "The Statue of Easter Island",
	"attribute": "Earth",
	"level": 4,
	"atk": 1100,
	"def": 1400,
	"type": "Rock",
	"guardian_star": ["Uranus","Mars"],
	"description": "Un enorme ídolo de piedra de la Isla de Pascua que dispara anillos láser por la boca.",
	"effects": [],
	"tags": ["earth","rock","statue"],
	"passcode": "10262698"
	},
	"000094": {
	"card_id": "000094",
	"card_type": "Monster",
	"card_name": "E. HERO Avian",
	"attribute": "Wind",
	"level": 4,
	"atk": 1000,
	"def": 1000,
	"type": "Warrior",
	"guardian_star": ["Saturn","Jupiter"],
	"description": "Un HÉROE Elemental alado que gira cruzando el cielo y manipula el viento. Su movimiento personal, Rompeplumas, le propina a la vileza un golpe desde el cielo.",
	"effects": [],
	"tags": ["hero","wind"],
	"passcode": "21844576"
	},
	"000095": {
	"card_id": "000095",
	"card_type": "Monster",
	"card_name": "E. HERO Burstinatrix",
	"attribute": "Fire",
	"level": 3,
	"atk": 1200,
	"def": 800,
	"type": "Warrior",
	"guardian_star": ["Mars","Mercury"],
	"description": "Una manipuladora de las llamas que es la primera mujer de los HÉROEs Elementales. Su Llamarada quema la vileza.",
	"effects": [],
	"tags": ["hero","fire","pyro"],
	"passcode": "58932615"
	},
	"000096": {
	"card_id": "000096",
	"card_type": "Monster",
	"card_name": "E. HERO Sparkman",
	"attribute": "Light",
	"level": 4,
	"atk": 1600,
	"def": 1400,
	"type": "Warrior",
	"guardian_star": ["Pluto","Sun"],
	"description": "Un HÉROE Elemental y guerrero de la luz hábil con muchos tipos de armamento. Su Llamarada Resplandeciente corta el camino de la vileza.",
	"effects": [],
	"tags": ["hero","thunder","light"],
	"passcode": "20721928"
	},
	"000097": {
	"card_id": "000097",
	"card_type": "Monster",
	"card_name": "E. HERO Clayman",
	"attribute": "Earth",
	"level": 4,
	"atk": 800,
	"def": 2000,
	"type": "Warrior",
	"guardian_star": ["Uranus","Jupiter"],
	"description": "Un HÉROE Elemental con un cuerpo de arcilla hecho para resistir. Protegerá a sus colegas HÉROEs Elementales a cualquier precio.",
	"effects": [],
	"tags": ["hero","earth","rock"],
	"passcode": "84327329"
	},
	"000098": {
	"card_id": "000098",
	"card_type": "Monster",
	"card_name": "E. HERO Bubbleman",
	"attribute": "Water",
	"level": 4,
	"atk": 800,
	"def": 1200,
	"type": "Warrior",
	"guardian_star": ["Neptune","Venus"],
	"description": "Un HÉROE Elemental y guerrero del agua hábil en combate y estratégico, suele apoyar a sus compañeros con su mente y gran visión.",
	"effects": [],
	"tags": ["hero","water","aqua"],
	"passcode": "79979666"
	},
	"000099": {
	"card_id": "000099",
	"card_type": "Monster",
	"card_name": "E. HERO Necroshade",
	"attribute": "Dark",
	"level": 5,
	"atk": 1600,
	"def": 1800,
	"type": "Warrior",
	"guardian_star": ["Moon","Mercury"],
	"description": "Un HÉROE Elemental y guerrero de la oscuridad, a pesar de sus métodos ha aprendido de ayudar a sus aliados, sus tácticas pueden considerarse viles, pero sus resultados son incuestionables.",
	"effects": [],
	"tags": ["hero","dark","fiend"],
	"passcode": "89252153"
	},
	"000100": {
	"card_id": "000100",
	"card_type": "Monster",
	"card_name": "E. HERO Bladedge",
	"attribute": "Earth",
	"level": 7,
	"atk": 2600,
	"def": 1800,
	"type": "Warrior",
	"guardian_star": ["Saturn","Uranus"],
	"description": "Un Heroe elemental que se ha vuelto tan poderoso como para atravesar las defensas con sus afiladas cuchillas, ni siquiera los mejores escudos pueden evitar salir dañados contra él.",
	"effects": [
		{
			"type": "on_attack",
			"action": "piercing_damage"
		}
	],
	"tags": ["hero","earth","warrior"],
	"passcode": "59793705"
	},
	"000101": {
	"card_id": "000101",
	"card_type": "Monster",
	"card_name": "E. HERO Wildheart",
	"attribute": "Earth",
	"level": 4,
	"atk": 1500,
	"def": 1600,
	"type": "Warrior",
	"guardian_star": ["Uranus","Jupiter"],
	"description": "Un HÉROE Elemental conocido por sus capacidades de supervivencia, se desenvuelve perfectamente en la naturaleza y sus grandes instintos le permiten sortear trampas con facilidad.",
	"effects": [
		{
			"type": "immune",
			"to": "traps"
		}
	],
	"tags": ["hero","beast-warrior","earth"],
	"passcode": "86188410"
},
	"000102": {
	"card_id": "000102",
	"card_type": "Monster",
	"card_name": "E. HERO Prisma",
	"attribute": "Light",
	"level": 4,
	"atk": 1700,
	"def": 1100,
	"type": "Warrior",
	"guardian_star": ["Sun","Venus"],
	"description": "Un HÉROE Elemental muy particular, su potencial es desconocido, sin embargo su poder es innegable, se cree que posee la capacidad de imitar todos los elementos.",
	"effects": [],
	"tags": ["hero","rock","light","earth","fire","water","dark","wind"],
	"passcode": "89312388"
	},
	"000103": {
	"card_id": "000103",
	"card_type": "Monster",
	"card_name": "E. HERO Flame Wingman",
	"attribute": "Wind",
	"level": 6,
	"atk": 2100,
	"def": 1200,
	"type": "Warrior",
	"guardian_star": ["Mars","Saturn"],
	"description": "Un HÉROE Elemental nacido de la unión del fuego y el viento, centrado completamente en su velocidad y ofensiva, sus habilidades le permiten utilizar la ofensiva de sus enemigos contra ellos.",
	"effects": [
		{
			"type": "on_destroy",
			"action": "inflict_destroyed_atk"
		}
	],
	"tags": ["hero","fire","pyro","wind"],
	"passcode": "35809262"
	},
	"000104": {
	"card_id": "000104",
	"card_type": "Monster",
	"card_name": "E. HERO Steam Healer",
	"attribute": "Water",
	"level": 5,
	"atk": 1800,
	"def": 1000,
	"type": "Warrior",
	"guardian_star": ["Sun","Neptune"],
	"description": "Un HÉROE Elemental cuya cualidad no es en sí el comabte, sin embargo puede aprovechar la energía de los rivales para sanar a sus aliados.",
	"effects": [
		{
			"type": "on_attack",
			"action": "recover_hp",
			"amount": 500
		}
	],
	"tags": ["hero","water","aqua"],
	"passcode": "81197327"
	},
	"000105": {
	"card_id": "000105",
	"card_type": "Monster",
	"card_name": "E. HERO Mariner",
	"attribute": "Water",
	"level": 4,
	"atk": 1400,
	"def": 1000,
	"type": "Warrior",
	"guardian_star": ["Saturn","Neptune"],
	"description": "Un HÉROE Elemental con la capacidad de sobrepasar las defensas del oponente, alcanza a su objetivo sin importar que.",
	"effects": [
		{
			"type": "on_attack",
			"action": "can_direct_attack"
		}
	],
	"tags": ["hero","water","aqua","wind"],
	"passcode": "14225239"
	},
	"000106": {
	"card_id": "000106",
	"card_type": "Monster",
	"card_name": "E. HERO Thunder Giant",
	"attribute": "Light",
	"level": 6,
	"atk": 2400,
	"def": 1500,
	"type": "Warrior",
	"guardian_star": ["Pluto","Uranus"],
	"description": "Un HÉROE Elemental con el poder suficiente para controlar las tormentas y el rayo, puede concentrar todo su poder en un poderoso trueno que elimina a cualquier oponente.",
	"effects": [
		{
			"type": "on_play",
			"action": "destroy_target_enemy"
		}
	],
	"tags": ["hero","thunder","earth","light"],
	"passcode": "61204971"
	},
	"000107": {
	"card_id": "000107",
	"card_type": "Monster",
	"card_name": "E. HERO Necroid Shaman",
	"attribute": "Dark",
	"level": 6,
	"atk": 1900,
	"def": 1800,
	"type": "Warrior",
	"guardian_star": ["Mercury","Uranus"],
	"description": "Un HÉROE Elemental que trascendió el mundo físico y conectó con el mundo espiritual, su habilidad le permite traer a sus aliados de nuevo al combate.",
	"effects": [
		{
			"type": "on_play",
			"action": "reborn_from_grave"
		}
	],
	"tags": ["hero","beast-warrior","spellcaster","dark"],
	"passcode": "81003500"
	},
	"000108": {
	"card_id": "000108",
	"card_type": "Monster",
	"card_name": "E. HERO Wild Wingman",
	"attribute": "Earth",
	"level": 8,
	"atk": 1900,
	"def": 2300,
	"type": "Warrior",
	"guardian_star": ["Pluto","Uranus"],
	"description": "Un HÉROE Elemental cuyos instintos han incrementado al nivel que puede predecir cualquier ataque, el viento que produce con sus alas es capaz de destruir hasta las trampas ocultas.",
	"effects": [
		{
			"type": "on_play",
			"action": "destroy_spell_trap"
		}
	],
	"tags": ["hero","beast-warrior","winged-beast","wind","earth"],
	"passcode": "55615891"
	},
	"000109": {
	"card_id": "000109",
	"card_type": "Monster",
	"card_name": "E. HERO Tempest",
	"attribute": "Wind",
	"level": 8,
	"atk": 2800,
	"def": 2800,
	"type": "Warrior",
	"guardian_star": ["Saturn","Neptune"],
	"description": "Un HÉROE Elemental que vuela por los cielos, tiene la capacidad de arrasar con campos enteros de un solo ataque.",
	"effects": [
		{
			"type": "on_play",
			"action": "destroy_all_monsters"
		}
	],
	"tags": ["hero","warrior","wind","earth","water"],
	"passcode": "83121692"
	},
	"000110": {
	"card_id": "000110",
	"card_type": "Monster",
	"card_name": "E. HERO Wildedge",
	"attribute": "Earth",
	"level": 8,
	"atk": 2650,
	"def": 2300,
	"type": "Warrior",
	"guardian_star": ["Pluto","Uranus"],
	"description": "Un HÉROE Elemental que ha masterizado el uso de la espada, sus ataques salvajes son impredecibles, es capáz de cortar a gran velocidad, siendo capaz de alcanzar a multiples oponentes en pocos instantes.",
	"effects": [
		{
			"type": "on_attack",
			"action": "multi_attack",
			"mode": "all_each"
		}
	],
	"tags": ["hero","beast-warrior","warrior","earth"],
	"passcode": "10526791"
	},
	"000111": {
	"card_id": "000111",
	"card_type": "Monster",
	"card_name": "E. HERO Rampart Blaster",
	"attribute": "Earth",
	"level": 6,
	"atk": 2000,
	"def": 2500,
	"type": "Warrior",
	"guardian_star": ["Mars","Uranus"],
	"description": "Un HÉROE Elemental maestro en el uso de artilleraía pesada, sus potentes misiles pueden destruir cualquier defensa.",
	"effects": [
		{
			"type": "on_attack",
			"action": "destroy_defense_monsters"
		}
	],
	"tags": ["hero","machine","warrior","earth","fire","cannon"],
	"passcode": "47737087"
	},
	"000112": {
	"card_id": "000112",
	"card_type": "Monster",
	"card_name": "E. HERO Shining Flare Wingman",
	"attribute": "Light",
	"level": 8,
	"atk": 2500,
	"def": 2100,
	"type": "Warrior",
	"guardian_star": ["Mars","Sun"],
	"description": "Un HÉROE Elemental nacido de la esperanza, su poder se alimenta de los deseos de sus aliados caídos, el brillo de sus alas quema las almas de los malvados.",
	"effects": [
		{
			"type": "on_field",
			"action": "increase_atk_def",
			"amount": 500,
			"stat": "atk",
			"condition": "hero_in_graveyard"
		},
		{
			"type": "on_destroy",
			"action": "inflict_destroyed_atk"
		}
	],
	"tags": ["hero","warrior","wind","fire","light"],
	"passcode": "25366484"
},
	"000113": {
	"card_id": "000113",
	"card_type": "Monster",
	"card_name": "E. HERO Mudballman",
	"attribute": "Earth",
	"level": 6,
	"atk": 1900,
	"def": 3000,
	"type": "Warrior",
	"guardian_star": ["Neptune","Uranus"],
	"description": "Un HÉROE Elemental que ha entrenado su defensa a un nivel que pocos alcanzan, su defensa se adapta a casi cualquier tipo de daño, saliendo ileso en la mayoría de enfrentamientos.",
	"effects": [],
	"tags": ["hero","earth","water"],
	"passcode": "52031567"
},
"000114": {
	"card_id": "000114",
	"card_type": "Monster",
	"card_name": "E. HERO Darkbright",
	"attribute": "Dark",
	"level": 6,
	"atk": 2000,
	"def": 1000,
	"type": "Warrior",
	"guardian_star": ["Sun","Moon"],
	"description": "Un HÉROE Elemental que ha logrado controlar la luz y la oscuridad, su aparición suele traer destrucción y justicia a la vez.",
	"effects": [
		{
			"type": "on_play",
			"action": "destroy_all_spell_trap"
		}
	],
	"tags": ["hero","dark","light"],
	"passcode": "41517968"
},
	"000115": {
	"card_id": "000115",
	"card_type": "Monster",
	"card_name": "Anthrosaurus",
	"attribute": "Earth",
	"level": 3,
	"atk": 1000,
	"def": 850,
	"type": "Dinosaur",
	"guardian_star": ["Uranus","Moon"],
	"description": "Dinosaurio con forma humanoide, su poder palidece en contra de otros dinosaurios pero su inteligencia lo compensa.",
	"effects": [],
	"tags": ["dinosaur","earth"],
	"passcode": "89904598"
	},
	"000116": {
	"card_id": "000116",
	"card_type": "Monster",
	"card_name": "Daemon Beaver",
	"attribute": "Earth",
	"level": 2,
	"atk": 400,
	"def": 600,
	"type": "Beast",
	"guardian_star": ["Moon","Uranus"],
	"description": "Una ardilla con cuernos y alas demoniacas, se desplaza por los aires con increíble velocidad.",
	"effects": [],
	"tags": ["beast","earth","wind"],
	"passcode": "75889523"
	},
	"000117": {
	"card_id": "000117",
	"card_type": "Monster",
	"card_name": "Frenzied Panda",
	"attribute": "Earth",
	"level": 4,
	"atk": 1200,
	"def": 1000,
	"type": "Beast",
	"guardian_star": ["Jupiter","Venus"],
	"description": "Una bestia descontrolada que lleva siempre una larga vara de bamboo con la que enfrenta a sus enemigos.",
	"effects": [],
	"tags": ["beast","earth","panda"],
	"passcode": "98818516"
	},
	"000118": {
	"card_id": "000118",
	"card_type": "Monster",
	"card_name": "Petit Dragon",
	"attribute": "Wind",
	"level": 2,
	"atk": 600,
	"def": 700,
	"type": "Dragon",
	"guardian_star": ["Saturn","Sun"],
	"description": "Un dragón muy pequeño conocido por sus feroces ataques.",
	"effects": [],
	"tags": ["wind","dragon"],
	"passcode": "75356564"
	},
	"000119": {
	"card_id": "000119",
	"card_type": "Monster",
	"card_name": "Penguin Knight",
	"attribute": "Water",
	"level": 3,
	"atk": 900,
	"def": 800,
	"type": "Aqua",
	"guardian_star": ["Uranus","Mercury"],
	"description": "Una criatura parecida a un pingüino que se desliza sobre su vientre para asestar un golpe con su espada extendida.",
	"effects": [],
	"tags": ["water","aqua","penguin"],
	"passcode": "36039163"
	},
	"000120": {
	"card_id": "000120",
	"card_type": "Monster",
	"card_name": "Happy Lover",
	"attribute": "Light",
	"level": 2,
	"atk": 800,
	"def": 500,
	"type": "Fairy",
	"guardian_star": ["Sun","Uranus"],
	"description": "Un angelito que dispara rayos de felicidad desde la joya en forma de corazón que lleva en la frente.",
	"effects": [],
	"tags": ["angel","fairy","light"],
	"passcode": "99030164"
	},
	"000121": {
	"card_id": "000121",
	"card_type": "Monster",
	"card_name": "Terra the Terrible",
	"attribute": "Earth",
	"level": 4,
	"atk": 1200,
	"def": 1300,
	"type": "Fiend",
	"guardian_star": ["Moon","Jupiter"],
	"description": "Conocida como habitante de los pantanos, esta criatura es una esbirro de las fuerzas oscuras.",
	"effects": [],
	"tags": ["golem","fiend","earth"],
	"passcode": "63308047"
	},
	"000122": {
	"card_id": "000122",
	"card_type": "Monster",
	"card_name": "Turtle Tiger",
	"attribute": "Water",
	"level": 4,
	"atk": 1000,
	"def": 1500,
	"type": "Aqua",
	"guardian_star": ["Neptune","Saturn"],
	"description": "Un tigre envuelto en un caparazón protector que ataca a sus enemigos con sus afilados colmillos.",
	"effects": [],
	"tags": ["turtle","beast","water","aqua"],
	"passcode": "37313348"
	},
	"000123": {
	"card_id": "000123",
	"card_type": "Monster",
	"card_name": "Key Mace",
	"attribute": "Light",
	"level": 1,
	"atk": 400,
	"def": 300,
	"type": "Fairy",
	"guardian_star": ["Neptune","Saturn"],
	"description": "Un pequeño ángel cuya ternura derrite los corazones de sus enemigos.",
	"effects": [],
	"tags": ["fairy","light"],
	"passcode": "01929294"
	},
	"000124": {
	"card_id": "000124",
	"card_type": "Monster",
	"card_name": "LALA Li-oon",
	"attribute": "Wind",
	"level": 2,
	"atk": 600,
	"def": 600,
	"type": "Thunder",
	"guardian_star": ["Pluto","Moon"],
	"description": "Protegida por el trueno, esta peligrosa nube ataca a sus enemigos con lluvia ácida.",
	"effects": [],
	"tags": ["cloud","thunder","wind"],
	"passcode": "09430387"
	},
	"000125": {
	"card_id": "000125",
	"card_type": "Monster",
	"card_name": "Fusionist",
	"attribute": "Earth",
	"level": 3,
	"atk": 900,
	"def": 700,
	"type": "Beast",
	"guardian_star": ["Jupiter","Moon"],
	"description": "Un gato monstruoso con alas y una cola larga e impresionante.",
	"effects": [],
	"tags": ["beast","earth","winged-beast"],
	"passcode": "01641882"
	},
	"000126": {
	"card_id": "000126",
	"card_type": "Monster",
	"card_name": "Genin",
	"attribute": "Light",
	"level": 3,
	"atk": 600,
	"def": 900,
	"type": "Spellcaster",
	"guardian_star": ["Venus","Sun"],
	"description": "Utiliza increíbles trucos de magia para engañar y destruir a sus enemigos.",
	"effects": [],
	"tags": ["spellcaster","light"],
	"passcode": "49370026"
},
	"000127": {
	"card_id": "000127",
	"card_type": "Monster",
	"card_name": "Masked Clown",
	"attribute": "Dark",
	"level": 3,
	"atk": 500,
	"def": 700,
	"type": "Warrior",
	"guardian_star": ["Mercury","Saturn"],
	"description": "Un guerrero danzante que despedaza a sus oponentes con una afilada guadaña.",
	"effects": [],
	"tags": ["clown","warrior","dark"],
	"passcode": "77581312"
},
	"000128": {
	"card_id": "000128",
	"card_type": "Monster",
	"card_name": "Alraune",
	"attribute": "Earth",
	"level": 3,
	"atk": 800,
	"def": 1000,
	"type": "Plant",
	"guardian_star": ["Jupiter","Neptune"],
	"description": "Una doncella nacida de entre las flores esparce polen venenoso contra sus oponentes.",
	"effects": [],
	"tags": ["plant","elf","earth"],
	"passcode": "14708569"
},
	"000129": {
	"card_id": "000129",
	"card_type": "Monster",
	"card_name": "Phantom Dewan",
	"attribute": "Dark",
	"level": 2,
	"atk": 700,
	"def": 600,
	"type": "Spellcaster",
	"guardian_star": ["Mercury","Jupiter"],
	"description": "Un mago que paraliza el movimiento de un enemigo con una simple maldición.",
	"effects": [],
	"tags": ["spellcaster","dark"],
	"passcode": "77603950"
},
	"000130": {
	"card_id": "000130",
	"card_type": "Monster",
	"card_name": "Claw Reacher",
	"attribute": "Dark",
	"level": 3,
	"atk": 1000,
	"def": 800,
	"type": "Fiend",
	"guardian_star": ["Mercury","Mars"],
	"description": "Sus brazos extensibles y sus garras afiladas como navajas hacen de este monstruo un oponente formidable.",
	"effects": [],
	"tags": ["fiend","dark"],
	"passcode": "41218256"
},
	"000131": {
	"card_id": "000131",
	"card_type": "Monster",
	"card_name": "Wetha",
	"attribute": "Water",
	"level": 3,
	"atk": 1000,
	"def": 900,
	"type": "Aqua",
	"guardian_star": ["Neptune","Saturn"],
	"description": "Un espíritu de la lluvia que puede invocar tifones y tormentas para arrasar con sus enemigos.",
	"effects": [],
	"tags": ["water","thunder","spellcaster"],
	"passcode": "96643568"
},
	"000132": {
	"card_id": "000132",
	"card_type": "Monster",
	"card_name": "Versago the Destroyer",
	"attribute": "Dark",
	"level": 3,
	"atk": 1100,
	"def": 900,
	"type": "Fiend",
	"guardian_star": ["Mercury","Saturn"],
	"description": "Señor de la destrucción nacido del corazón de las tinieblas, esta criatura puede invocar tormentas para destruir a sus oponentes.",
	"effects": [],
	"tags": ["dark","fiend"],
	"passcode": "50259460"
},
	"000133": {
	"card_id": "000133",
	"card_type": "Monster",
	"card_name": "Sectarian of Secrets",
	"attribute": "Dark",
	"level": 2,
	"atk": 700,
	"def": 500,
	"type": "Fiend",
	"guardian_star": ["Mercury","Saturn"],
	"description": "Señor de la destrucción nacido del corazón de las tinieblas, esta criatura puede invocar tormentas para destruir a sus oponentes.",
	"effects": [],
	"tags": ["dark","robe","spellcaster"],
	"passcode": "15507080"
},
	"000134": {
	"card_id": "000134",
	"card_type": "Monster",
	"card_name": "Unknown Warrior of Fiend",
	"attribute": "Dark",
	"level": 3,
	"atk": 1000,
	"def": 500,
	"type": "Fiend",
	"guardian_star": ["Mercury","Saturn"],
	"description": "La velocidad de este guerrero crea un intenso vacío capaz de cortar la piel de demonios y bestias.",
	"effects": [],
	"tags": ["warrior","dark","fiend"],
	"passcode": "97360116"
},
	"000135": {
	"card_id": "000135",
	"card_type": "Monster",
	"card_name": "Queen of Swords",
	"attribute": "Wind",
	"level": 3,
	"atk": 900,
	"def": 700,
	"type": "Warrior",
	"guardian_star": ["Saturn","Venus"],
	"description": "Una reina de espadas prácticamente inigualable en su dominio de todas las armas blancas imaginables por el hombre.",
	"effects": [],
	"tags": ["warrior","elf","wind"],
	"passcode": "51371017"
},
	"000136": {
	"card_id": "000136",
	"card_type": "Monster",
	"card_name": "Violent Rain",
	"attribute": "Water",
	"level": 4,
	"atk": 1550,
	"def": 800,
	"type": "Aqua",
	"guardian_star": ["Neptune","Mercury"],
	"description": "Un cúmulo de nubes que ha obtenido consciencia, suele estar en calma pero sus violentas tormentas se desatan ante cualquier molestia.",
	"effects": [],
	"tags": ["water","thunder","cloud","aqua"],
	"passcode": "94042337"
},
	"000137": {
	"card_id": "000137",
	"card_type": "Monster",
	"card_name": "Water Magician",
	"attribute": "Water",
	"level": 4,
	"atk": 1400,
	"def": 1000,
	"type": "Aqua",
	"guardian_star": ["Neptune","Mercury"],
	"description": "Esta criatura rodea a sus oponentes con grandes cantidades de agua, los sofoca hasta dejarlos inconscientes.",
	"effects": [],
	"tags": ["water","spellcaster","aqua"],
	"passcode": "93343894"
},
	"000138": {
	"card_id": "000138",
	"card_type": "Monster",
	"card_name": "Giant Red Seasnake",
	"attribute": "Water",
	"level": 4,
	"atk": 1800,
	"def": 800,
	"type": "Sea Serpent",
	"guardian_star": ["Neptune","Sun"],
	"description": "Una inmensa serpiente marina que devora todo a su paso.",
	"effects": [],
	"tags": ["water","sea-serpent"],
	"passcode": "58831685"
},
	"000139": {
	"card_id": "000139",
	"card_type": "Monster",
	"card_name": "Giant Flea",
	"attribute": "Earth",
	"level": 4,
	"atk": 1500,
	"def": 1200,
	"type": "Insect",
	"guardian_star": ["Jupiter","Venus"],
	"description": "Una inmensa pulga chupasangre cuya saliva es capaz de disolver a sus víctimas desde el interior.",
	"effects": [],
	"tags": ["insect","earth"],
	"passcode": "41762634"
},
	"000140": {
	"card_id": "000140",
	"card_type": "Monster",
	"card_name": "Burning Beast",
	"attribute": "Fire",
	"level": 4,
	"atk": 1500,
	"def": 1000,
	"type": "Pyro",
	"guardian_star": ["Mars","Venus"],
	"description": "Una bestia cuadrúpeda cuyo cuerpo está formado por magma y rocas a alta temperatura, aplasta a sus oponentes con su peso, muchos quedan calcinados con su simple presencia.",
	"effects": [],
	"tags": ["beast","fire","pyro"],
	"passcode": "59364406"
},
	"000141": {
	"card_id": "000141",
	"card_type": "Monster",
	"card_name": "Tongyo",
	"attribute": "Water",
	"level": 4,
	"atk": 1350,
	"def": 800,
	"type": "Fish",
	"guardian_star": ["Neptune","Moon"],
	"description": "Extraño pez que se alimenta de la fuerza vital de aquellos peces más pequeños que quedan atrapados en su lengua.",
	"effects": [],
	"tags": ["fish","water","aqua"],
	"passcode": "69572024"
},
	"000142": {
	"card_id": "000142",
	"card_type": "Monster",
	"card_name": "Freezing Beast",
	"attribute": "Water",
	"level": 4,
	"atk": 1500,
	"def": 1000,
	"type": "Aqua",
	"guardian_star": ["Neptune","Moon"],
	"description": "Una criatura compuesta de hielo y agua, su simple presencia puede congelar hasta la muerte a aquellos incautos que se adentren en su territorio.",
	"effects": [],
	"tags": ["ice","water","aqua","beast"],
	"passcode": "85359414"
},
	"000143": {
	"card_id": "000143",
	"card_type": "Monster",
	"card_name": "Granadora",
	"attribute": "Water",
	"level": 4,
	"atk": 1900,
	"def": 700,
	"type": "Reptile",
	"guardian_star": ["Neptune","Saturn"],
	"description": "Extraño reptil que se guía por sus instintos, mora en lagos y rios a la espera de grandes presas.",
	"effects": [],
	"tags": ["reptile","water"],
	"passcode": "13944422"
},
	"000144": {
	"card_id": "000144",
	"card_type": "Monster",
	"card_name": "Flying Penguin",
	"attribute": "Water",
	"level": 4,
	"atk": 1200,
	"def": 1000,
	"type": "Aqua",
	"guardian_star": ["Neptune","Jupiter"],
	"description": "Curioso pinguino con la capacidad de volar, capáz de atravesar grandes distancias volando con las alas de su cabeza.",
	"effects": [],
	"tags": ["w-beast","water","aqua"],
	"passcode": "05628232"
},
	"000145": {
	"card_id": "000145",
	"card_type": "Monster",
	"card_name": "Roaring Ocean Snake",
	"attribute": "Water",
	"level": 6,
	"atk": 2100,
	"def": 1800,
	"type": "Aqua",
	"guardian_star": ["Neptune","Mars"],
	"description": "Una inmensa serpiente marina que acaba con flotas enteras creando mareas descomunales.",
	"effects": [],
	"tags": ["sea-serpent","water","aqua"],
	"passcode": "19066538"
},
	"000146": {
	"card_id": "000146",
	"card_type": "Monster",
	"card_name": "Kuwagata α",
	"attribute": "Earth",
	"level": 4,
	"atk": 1250,
	"def": 1000,
	"type": "Aqua",
	"guardian_star": ["Jupiter","Mercury"],
	"description": "Un insecto humanoide cuya sed de sangre parece insaciable, busca oponentes fuertes y se enfrenta a cualquiera que le plante cara.",
	"effects": [],
	"tags": ["b-warrior","insect","earth"],
	"passcode": "60802233"
},
	"000147": {
	"card_id": "000147",
	"card_type": "Monster",
	"card_name": "Rude Kaiser",
	"attribute": "Earth",
	"level": 5,
	"atk": 1800,
	"def": 1600,
	"type": "Beast-Warrior",
	"guardian_star": ["Uranus","Sun"],
	"description": "Porta un hacha en cada mano para despedazar a sus presas.",
	"effects": [],
	"tags": ["b-warrior","reptile","earth"],
	"passcode": "26378150"
},
	"000148": {
	"card_id": "000148",
	"card_type": "Monster",
	"card_name": "Giga-tech Wolf",
	"attribute": "Earth",
	"level": 4,
	"atk": 1200,
	"def": 1400,
	"type": "Machine",
	"guardian_star": ["Jupiter","Uranus"],
	"description": "Un lobo hecho completamente de acero, sus garras metalicas pueden atravesar cualquier defensa.",
	"effects": [],
	"tags": ["beast","machine","earth"],
	"passcode": "08471389"
},
	"000149": {
	"card_id": "000149",
	"card_type": "Monster",
	"card_name": "Ocubeam",
	"attribute": "Light",
	"level": 5,
	"atk": 1550,
	"def": 1650,
	"type": "Fairy",
	"guardian_star": ["Saturn","Venus"],
	"description": "De aspecto aterrador, esta criatura utiliza sus grandes ojos y orejas para detectar cualquier movimiento.",
	"effects": [],
	"tags": ["fairy","beast","light"],
	"passcode": "86088138"
},
	"000150": {
	"card_id": "000150",
	"card_type": "Monster",
	"card_name": "Uraby",
	"attribute": "Earth",
	"level": 4,
	"atk": 1500,
	"def": 800,
	"type": "Dinosaur",
	"guardian_star": ["Uranus","Mars"],
	"description": "Rápido y ágil, este dinosaurio destroza a sus enemigos con sus afiladas garras, su ataque no se detiene hasta que su criatura quede hecha pedazos.",
	"effects": [],
	"tags": ["dinosaur","earth"],
	"passcode": "01784619"
},
	"000151": {
	"card_id": "000151",
	"card_type": "Monster",
	"card_name": "Cyber Saurus",
	"attribute": "Earth",
	"level": 5,
	"atk": 1800,
	"def": 1400,
	"type": "Machine",
	"guardian_star": ["Uranus","Sun"],
	"description": "Un dinosaurio mecánico equipado con un cañón de rayos.",
	"effects": [],
	"tags": ["dinosaur","earth","machine"],
	"passcode": "89112729"
},
	"000152": {
	"card_id": "000152",
	"card_type": "Monster",
	"card_name": "Thunder Dragon",
	"attribute": "Light",
	"level": 5,
	"atk": 1600,
	"def": 1500,
	"type": "Thunder",
	"guardian_star": ["Pluto","Jupiter"],
	"description": "Un dragón que invoca truenos y relámpagos para atacar a sus oponentes.",
	"effects": [],
	"tags": ["thunder","dragon"],
	"passcode": "31786629"
},
	"000153": {
	"card_id": "000153",
	"card_type": "Monster",
	"card_name": "Bean Soldier",
	"attribute": "Earth",
	"level": 4,
	"atk": 1400,
	"def": 1300,
	"type": "Plant",
	"guardian_star": ["Jupiter","Uranus"],
	"description": "Un guerrero vegetal que ataca con una combinación de golpes de espada y proyectiles de guisantes.",
	"effects": [],
	"tags": ["plant","warrior"],
	"passcode": "84990171"
},
	"000154": {
	"card_id": "000154",
	"card_type": "Monster",
	"card_name": "Mavelus",
	"attribute": "Wind",
	"level": 4,
	"atk": 1300,
	"def": 900,
	"type": "Winged Beast",
	"guardian_star": ["Mars","Mercury"],
	"description": "Esta criatura, emparentada con el fénix, habita en las montañas. Su aliento de fuego es extremadamente abrasador.",
	"effects": [],
	"tags": ["fire","pyro","w-beast"],
	"passcode": "59036972"
},
	"000155": {
	"card_id": "000155",
	"card_type": "Monster",
	"card_name": "Cockroach Knight",
	"attribute": "Earth",
	"level": 3,
	"atk": 800,
	"def": 900,
	"type": "Insect",
	"guardian_star": ["Jupiter","Venus"],
	"description": "Una cucaracha guerrera que se esconde en espacios reducidos y emerge para atacar a sus enemigos.",
	"effects": [],
	"tags": ["insect","warrior","earth"],
	"passcode": "33413638"
},
	"000156": {
	"card_id": "000156",
	"card_type": "Monster",
	"card_name": "Spike Seadra",
	"attribute": "Water",
	"level": 5,
	"atk": 1600,
	"def": 1300,
	"type": "Sea Serpent",
	"guardian_star": ["Pluto","Mercury"],
	"description": "Utilizando las púas que brotan de su cuerpo, esta criatura apuñala a sus oponentes y los inunda de electricidad.",
	"effects": [],
	"tags": ["sea-serpent","water","dragon"],
	"passcode": "85326399"
},
	"000157": {
	"card_id": "000157",
	"card_type": "Monster",
	"card_name": "Serpent Night Dragon",
	"attribute": "Dark",
	"level": 7,
	"atk": 2350,
	"def": 2400,
	"type": "Dragon",
	"guardian_star": ["Mercury","Pluto"],
	"description": "Un dragón creado a partir del alma de un caballero malvado.",
	"effects": [],
	"tags": ["sea-serpent","water","warrior"],
	"passcode": "66516792"
},
	"000158": {
	"card_id": "000158",
	"card_type": "Monster",
	"card_name": "Tripwire Beast",
	"attribute": "Earth",
	"level": 4,
	"atk": 1200,
	"def": 1300,
	"type": "Thunder",
	"guardian_star": ["Pluto","Saturn"],
	"description": "Una extraña bestia que se oculta en cuevas o madrigueras, ataca a sus presas con ondas electromagnéticas.",
	"effects": [],
	"tags": ["beast","thunder"],
	"passcode": "45042329"
},
	"000159": {
	"card_id": "000159",
	"card_type": "Monster",
	"card_name": "Tatsunootoshigo",
	"attribute": "Earth",
	"level": 5,
	"atk": 1350,
	"def": 1600,
	"type": "Thunder",
	"guardian_star": ["Neptune","Mercury"],
	"description": "Un monstruo marino de rápidos movimientos que tiene cuerpo de caballo y de pez.",
	"effects": [],
	"tags": ["fish","beast","earth"],
	"passcode": "47922711"
},
	"000160": {
	"card_id": "000160",
	"card_type": "Monster",
	"card_name": "Marine Beast",
	"attribute": "Water",
	"level": 5,
	"atk": 1700,
	"def": 1600,
	"type": "Thunder",
	"guardian_star": ["Neptune","Mercury"],
	"description": "Una criatura marina con dientes afilados que no suelta a su víctima una vez que la atrapa.",
	"effects": [],
	"tags": ["fish","beast","earth"],
	"passcode": "29929832"
},
	"000161": {
	"card_id": "000161",
	"card_type": "Monster",
	"card_name": "Basic Insect",
	"attribute": "Earth",
	"level": 2,
	"atk": 500,
	"def": 700,
	"type": "Insect",
	"guardian_star": ["Jupiter","Pluto"],
	"description": "Esta criatura, que suele desplazarse en enjambres, tiene como hábitat ideal el bosque.",
	"effects": [],
	"tags": ["insect","earth"],
	"passcode": "89091579"
},
	"000162": {
	"card_id": "000162",
	"card_type": "Monster",
	"card_name": "Boo Koo",
	"attribute": "Dark",
	"level": 2,
	"atk": 650,
	"def": 500,
	"type": "Spellcaster",
	"guardian_star": ["Sun","Jupiter"],
	"description": "Un mago de los libros con página tras página de poderosos hechizos.",
	"effects": [],
	"tags": ["spellcaster","dark","book"],
	"passcode": "68963107"
},
	"000163": {
	"card_id": "000163",
	"card_type": "Monster",
	"card_name": "Droll Bird",
	"attribute": "Wind",
	"level": 2,
	"atk": 600,
	"def": 500,
	"type": "Winged Beast",
	"guardian_star": ["Saturn","Moon"],
	"description": "Con un grito de guerra que hiela la sangre de su oponente, esta criatura ataca con su enorme pico.",
	"effects": [],
	"tags": ["w-beast","wind"],
	"passcode": "68963107"
},
	"000164": {
	"card_id": "000164",
	"card_type": "Monster",
	"card_name": "Bladefly",
	"attribute": "Wind",
	"level": 2,
	"atk": 600,
	"def": 700,
	"type": "Insect",
	"guardian_star": ["Jupiter","Moon"],
	"description": "Una mosca monstruosa que se abalanza con sus afilados brazos extendidos hacia adelante, como espadas. Las ventizcas que provocan sus alas ayudan a sus aliados a alzar vuelo.",
	"effects": [
		{
			"type": "on_field",
			"action": "increase_atk_def",
			"amount": 300,
			"stat": "atk",
			"target": "wind_allies"
		}
	],
	"tags": ["insect","wind"],
	"passcode": "28470714"
	},
	"000165": {
	"card_id": "000165",
	"card_type": "Monster",
	"card_name": "Dharma Cannon",
	"attribute": "Dark",
	"level": 2,
	"atk": 900,
	"def": 500,
	"type": "Machine",
	"guardian_star": ["Moon","Mercury"],
	"description": "Un monstruo mecánico de gran precisión, cubierto de cañones de gran calibre.",
	"effects": [],
	"tags": ["machine","dark","cannon"],
	"passcode": "96967123"
},
	"000166": {
	"card_id": "000166",
	"card_type": "Monster",
	"card_name": "Fiend Krakenon",
	"attribute": "Water",
	"level": 4,
	"atk": 1200,
	"def": 1400,
	"type": "Aqua",
	"guardian_star": ["Neptune","Venus"],
	"description": "Un calamar gigante que aparece repentinamente desde las profundidades del mar para atacar a enemigos desprevenidos.",
	"effects": [],
	"tags": ["tentacle","water","aqua"],
	"passcode": "77456781"
},
	"000167": {
	"card_id": "000167",
	"card_type": "Monster",
	"card_name": "Hinotama Soul",
	"attribute": "Fire",
	"level": 2,
	"atk": 600,
	"def": 500,
	"type": "Aqua",
	"guardian_star": ["Mars","Uranus"],
	"description": "Una criatura de fuego intensamente caliente que embiste todo lo que se interpone en su camino.",
	"effects": [],
	"tags": ["fire","pyro","ball"],
	"passcode": "96851799"
},
	"000168": {
	"card_id": "000168",
	"card_type": "Monster",
	"card_name": "Swordsman from a Foreign Land",
	"attribute": "Earth",
	"level": 1,
	"atk": 250,
	"def": 250,
	"type": "Warrior",
	"guardian_star": ["Uranus","Venus"],
	"description": "Un guerrero oriental armado con una espada maldita. Aquellos a los que logra cortar con su hoja encuentran una muerte segura.",
	"effects": [
		{
			"type": "on_destroy",
			"action": "kill_destroyer_next_EP"
		}
	],
	"tags": ["samurai","warrior","earth"],
	"passcode": "85255550"
},
	"000169": {
	"card_id": "000169",
	"card_type": "Monster",
	"card_name": "The Drdek",
	"attribute": "Dark",
	"level": 3,
	"atk": 700,
	"def": 800,
	"type": "Fiend",
	"guardian_star": ["Moon","Saturn"],
	"description": "Una criatura con forma de ojo y patas para saltar muy alto y asestar golpes finales con sus afiladas garras.",
	"effects": [],
	"tags": ["dark","fiend","eye","hand"],
	"passcode": "08944575"
},
	"000170": {
	"card_id": "000170",
	"card_type": "Monster",
	"card_name": "Zone Eater",
	"attribute": "Water",
	"level": 1,
	"atk": 250,
	"def": 200,
	"type": "Aqua",
	"guardian_star": ["Neptune","Sun"],
	"description": "Una criatura marina que engulle a sus enemigos y los digiere lentamente. Aquellos a los que logra alcanzar con su veneno encuentran una muerte segura.",
	"effects": [
		{
			"type": "on_destroy",
			"action": "kill_destroyer_next_EP"
		}
	],
	"tags": ["water","aqua"],
	"passcode": "86100785"
},
	"000171": {
	"card_id": "000171",
	"card_type": "Monster",
	"card_name": "Serpent Marauder",
	"attribute": "Earth",
	"level": 2,
	"atk": 700,
	"def": 600,
	"type": "Reptile",
	"guardian_star": ["Neptune","Sun"],
	"description": "Una serpiente con un solo ojo que exhala un aliento helado para congelar a sus oponentes.",
	"effects": [],
	"tags": ["reptile","snake","earth"],
	"passcode": "86100785"
},
	"000172": {
	"card_id": "000172",
	"card_type": "Monster",
	"card_name": "Fiend Sword",
	"attribute": "Dark",
	"level": 4,
	"atk": 1400,
	"def": 800,
	"type": "Warrior",
	"guardian_star": ["Moon","Mercury"],
	"description": "Pocos han escapado a la maldición de esta criatura. Aquellos que lo han logrado han obtenido un poder incalculable.",
	"effects": [],
	"tags": ["weapon","dark","sword"],
	"passcode": "22855882"
},
	"000173": {
	"card_id": "000173",
	"card_type": "Monster",
	"card_name": "Hitotsu-me Giant",
	"attribute": "Earth",
	"level": 4,
	"atk": 1200,
	"def": 1000,
	"type": "Beast-Warrior",
	"guardian_star": ["Moon","Mars"],
	"description": "Un gigante de un solo ojo con un cuerpo poderoso, hecho para asestar golpes devastadores.",
	"effects": [],
	"tags": ["golem","earth","b-warrior"],
	"passcode": "76184692"
},
	"000174": {
	"card_id": "000174",
	"card_type": "Monster",
	"card_name": "Golgoil",
	"attribute": "Earth",
	"level": 4,
	"atk": 900,
	"def": 1600,
	"type": "Machine",
	"guardian_star": ["Venus","Neptune"],
	"description": "Un enorme gólem de hierro que aparece de una grieta dimensional.",
	"effects": [],
	"tags": ["golem","machine","earth"],
	"passcode": "07526150"
},
	"000175": {
	"card_id": "000175",
	"card_type": "Monster",
	"card_name": "Fungi of the Musk",
	"attribute": "Dark",
	"level": 1,
	"atk": 400,
	"def": 300,
	"type": "Fiend",
	"guardian_star": ["Jupiter","Moon"],
	"description": "Un monstruo que segrega ácido por sus poros para derretir todo lo que toca su piel.",
	"effects": [],
	"tags": ["dark","fiend","plant"],
	"passcode": "53830602"
},
	"000176": {
	"card_id": "000176",
	"card_type": "Monster",
	"card_name": "Blast Juggler",
	"attribute": "Fire",
	"level": 3,
	"atk": 800,
	"def": 900,
	"type": "Machine",
	"guardian_star": ["Mars","Venus"],
	"description": "Un dispositivo caminante que disfruta aniquilando enemigos haciéndolos explotar.",
	"effects": [],
	"tags": ["fire","machine","bomb"],
	"passcode": "70138455"
},
	"000177": {
	"card_id": "000177",
	"card_type": "Monster",
	"card_name": "Wood Clown",
	"attribute": "Earth",
	"level": 3,
	"atk": 800,
	"def": 1200,
	"type": "Warrior",
	"guardian_star": ["Mercury","Mars"],
	"description": "Una criatura con una sonrisa perturbadora que empuña una guadaña para repeler los golpes enemigos.",
	"effects": [],
	"tags": ["earth","clown","warrior"],
	"passcode": "17511156"
},
	"000178": {
	"card_id": "000178",
	"card_type": "Monster",
	"card_name": "Madjinn Gunn",
	"attribute": "Dark",
	"level": 2,
	"atk": 600,
	"def": 800,
	"type": "Fiend",
	"guardian_star": ["Moon","Jupiter"],
	"description": "Un arma viviente que dispara proyectiles por la boca.",
	"effects": [],
	"tags": ["dark","cannon","fiend"],
	"passcode": "43905751"
},
	"000179": {
	"card_id": "000179",
	"card_type": "Monster",
	"card_name": "Dark Titan of Terror",
	"attribute": "Dark",
	"level": 4,
	"atk": 1300,
	"def": 1100,
	"type": "Fiend",
	"guardian_star": ["Mercury","Jupiter"],
	"description": "Un espíritu que, según se dice, habita en el mundo de los sueños. Ataca a sus enemigos mientras duermen.",
	"effects": [],
	"tags": ["dark","golem","fiend"],
	"passcode": "89494469"
},
	"000180": {
	"card_id": "000180",
	"card_type": "Monster",
	"card_name": "Beautiful Headhuntress",
	"attribute": "Earth",
	"level": 4,
	"atk": 1600,
	"def": 800,
	"type": "Warrior",
	"guardian_star": ["Mercury","Saturn"],
	"description": "Una encantadora maestra de la espada con movimientos muy ágiles.",
	"effects": [],
	"tags": ["earth","warrior"],
	"passcode": "16899564"
},
	"000181": {
	"card_id": "000181",
	"card_type": "Monster",
	"card_name": "Guardian of the Labyrinth",
	"attribute": "Earth",
	"level": 4,
	"atk": 1000,
	"def": 1200,
	"type": "Warrior",
	"guardian_star": ["Pluto","Mercury"],
	"description": "Un guerrero que custodia la entrada al inframundo.",
	"effects": [],
	"tags": ["earth","warrior","armored"],
	"passcode": "89272878"
},
	"000182": {
	"card_id": "000182",
	"card_type": "Monster",
	"card_name": "Haniwa",
	"attribute": "Earth",
	"level": 2,
	"atk": 500,
	"def": 500,
	"type": "Rock",
	"guardian_star": ["Uranus","Jupiter"],
	"description": "Un muñeco de barro que protege los tesoros en las tumbas de los antiguos reyes.",
	"effects": [],
	"tags": ["earth","rock","puppet"],
	"passcode": "84285623"
},
	"000183": {
	"card_id": "000183",
	"card_type": "Trap",
	"card_name": "Mirror Force",
	"attribute": "trap",
	"level": 0,
	"atk": 0,
	"def": 0,
	"type": "Normal",
	"guardian_star": [],
	"description": "Cuando un monstruo del adversario declara un ataque: destruye todos los monstruos en Posición de Ataque de tu adversario.",
	"effects": [
				{
			"type": "triggered",
			"trigger": "opponent_attack_declared",
			"action": "destroy_attackers_in_attack_position",
			"condition_params": {
				"only_attack_position": true
			}
		}
	],
	"tags": [],
	"passcode": "44095762"
},
	"000184": {
	"card_id": "000184",
	"card_type": "Trap",
	"card_name": "Trap Hole",
	"attribute": "trap",
	"level": 0,
	"atk": 0,
	"def": 0,
	"type": "Normal",
	"guardian_star": [],
	"description": "Cuando tu adversario Invoca de Modo Normal o Volteo un monstruo con 1000 ATK o más: selecciona ese monstruo; destruye ese objetivo.",
	"effects": [
		{
			"type": "triggered",
			"trigger": "opponent_monster_played",
			"action": "destroy_target_enemy",
			"condition_params": {
				"min_atk": 1000
			}
		}
	],
	"tags": ["counter", "destruction"],
	"passcode": "04206964"
},
}
